docs/.vuepress/config.js, docs/project/README.md, docs/project/related-projects.md
This should create an MVP Project section:
- Removed irrelevant sections in config.js
- Updated links and text
=> Update Project section

README.md
Notes about where to edit navigation and content. I keep having to remind myself of the locations, so figured I'd write this up for others.
=> Add "Code organization" section to readme

docs/.vuepress/config.js, docs/community/contribute/code-persona.md, docs/community/contribute/ways-to-contribute.md, docs/community/contribute/writing-guide.md
Pair programmed with @mishmosh
=> update community docs

README.md, docs/.vuepress/config.js, docs/community/contribute/grammar-formatting-and-style.md
Neflify updated their system to host at .app instead of .com. This PR makes the appropriate updates.
=> update Netlify URL

docs/.vuepress/config.js, docs/concepts/why-filecoin.md, docs/introduction/why-filecoin.md
[**Rendered page**](https://deploy-preview-24--filecoin-docs.netlify.com/concepts/why-filecoin/)
I’m seeking a proof-read of this new page that describes why Filecoin is compelling.
Thank you!
=> Added "Why Filecoin?" page

docs/community/contribute/contribution-tutorial.md
Addresses all TODOs and cleans up remaining IPFS mentions.
=> Update contribution tutorial

docs/how-to/build-wallets-signing-tools-api-clients.md
Libaries > Lib**r**aries (missing r)
=> Fix typo in subtitle

docs/.vuepress/config.js, docs/.vuepress/theme/components/Home.vue, docs/how-to/store-making-deals.md, docs/how-to/store-making-storage-deals.md
- Adds content to storage deals section
- Rename file & titles to store-making-storage-deals.md (including changes to config.js and home.vue)
@terichadbourne there is 1 todo to improve wording for a headline, would love any suggestions.
=> Add storage deals section

docs/introduction/README.md
- Intro paragraph
- Links to 3 subpages
=> Basic content for introduction landing page

docs/.vuepress/theme/styles/index.styl
=> fix: calc left margin to allow for visible scrollbar

docs/introduction/filecoin-compared-to.md
- Swap position of storage providers & bitcoin sections
=> Updates to Compare page

docs/.vuepress/config.js
HOLD until we move site to docs.filecoin.io
=> ON HOLD: Update domain in config

docs/.vuepress/theme/components/Home.vue, docs/how-to/build-interacting-with-the-network.md, docs/how-to/build-sample-architectures.md, docs/how-to/build-wallets-signing-tools-api-clients.md, docs/how-to/install-filecoin.md, docs/how-to/store-large-files.md, docs/how-to/store-making-storage-deals.md, docs/how-to/store-prepare-data.md, docs/how-to/store-retrieving-data.md, docs/how-to/store-tokens.md
=> Capitalization fixes

docs/.vuepress/config.js, docs/introduction/ipfs-and-filecoin.md
This PR includes the initial reviewed draft for the IPFS and Filecoin page (ref. #72). Our next steps are to brainstorm use-case howtos for the bottom of the doc, followed by a final proofread.
=> IPFS and Filecoin page addition

docs/how-to/build-interacting-with-the-network.md
Adding the links that @eshon shared in slack. Feel free to copyedit, and merge directly if approved.
=> add devnet faucet and dashboard links

docs/how-to/build-interacting-with-the-network.md
Update to latest interopnet branch instructions
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1591641975206700
=> Update interopnet version

docs/how-to/build-interacting-with-the-network.md
To 6.16.0 based on yesterday's release.
=> Bump interopnet version

docs/how-to/build-wallets-signing-tools-api-clients.md
Also order API clients to list Lotus flavoured APIs first.
=> Add filecoin-ruby

docs/.vuepress/config.js, docs/how-to/mining.md
Solves #71 
This PR includes the initial draft for the new mining section of the docs (details in above ticket). Will be fleshing it out a lot more this afternoon, but any notes in the meantime would be greatly appreciated.
=> Mining page added

docs/.vuepress/config.js, package-lock.json, package.json
Refactor app build scripts to work with [`vuepress-plugin-ipfs`](https://github.com/cwaring/vuepress-plugin-ipfs) correctly
=> feat: setup vuepress-plugin-ipfs

docs/.vuepress/config.js, package-lock.json, package.json
Configure sitemap and robots plugins to improve SEO
=> feat: setup robots & sitemap

docs/build/README.md, docs/build/core-products/protocol-implementations.md, docs/build/examples/sample-architectures.md, docs/community/README.md, docs/community/contribute/contribution-tutorial.md, docs/community/contribute/grammar-formatting-and-style.md, docs/community/contribute/ways-to-contribute.md, docs/community/contribute/writing-guide.md, docs/how-to/store/large-files.md, docs/how-to/store/prepare-data.md, docs/mine/mining.md, docs/project/README.md
=> fix: fix all CI reported 404s

docs/mine/mining.md
WIP PR for the mining page notes in #102
=> Mining page expansions

docs/.vuepress/theme/components/Page.vue, docs/.vuepress/theme/styles/index.styl
Quick revision to move the page-nav inline with the content
=> fix: mv page-nav

docs/build/examples/meme-marketplace/overview.md, docs/build/examples/simple-pinning-service/overview.md, docs/build/start-building/interacting-with-the-network.md, docs/how-to/install-filecoin.md
In this PR:
- Specify how to connect to Nerpa devnet in interacting with the network guide
- Call this info out more clearly in the "Install Filecoin" section
- Add links to codebase and demo video for the Meme Marketplace and Simple Pinning Service examples
=> Nerpa devnet

docs/build/start-building/interacting-with-the-network.md
This PR was created in response to comments in filecoin-project/filecoin-docs#133.
=> fix: Amendments to Nerpa devnet

docs/.vuepress/head.js
=> fix: favicon 404 in Chrome

docs/.vuepress/theme/components/Home.vue
=> fix how-to links on homepage

docs/.vuepress/config.js, package-lock.json, package.json
In response to #131, added [medium-zoom plugin](https://vuepress.github.io/en/plugins/medium-zoom/) to enable zoom functionality for images.
Demo of functionality here: https://imgur.com/a/PAArhD3
=> feat: medium-zoom for images

docs/build/examples/network-inspector/step-1-start-lotus-devnet-and-go-ipfs.md, docs/build/examples/network-inspector/step-2-run-the-react-app.md, docs/build/examples/network-inspector/step-3-set-up-the-lotus-and-go-ipfs-api-clients.md, docs/build/examples/network-inspector/step-4-explore-the-filecoin-network-inspector-app.md
Current style:
With standard JS formatting (used across PL) and syntax enabled:
cc @pooja
=> fix: syntax highlighting & JS formatting

docs/.vuepress/config.js, docs/how-to/build-filecoin-web-applications-with-textile-and-react.md, docs/how-to/store/large-files.md, package-lock.json
* New documentation for building web applications for Filecoin.
* A document we can update over time as more functionality is added over time.
* Hope you are all well :)
* Added to `how-to` since it is a tutorial.
=> Adds documentation for building filecoin application docs

docs/build/start-building/interacting-with-the-network.md
And remove broken link to https://filecoin.io/testnet
=> Update testnet info

docs/build/start-building/interacting-with-the-network.md
- Updating hosted node endpoints paragraph
- Section header small change
- Small formatting change
=> Update to hosted node endpoints description

docs/build/start-building/interacting-with-the-network.md
=> Adding powergate + moving things around

docs/.vuepress/config.js, docs/.vuepress/theme/components/Home.vue, docs/mine/connectivity.md
Solves #178 
This PR includes an initial draft for an 'improving connectivity' page in the `/mine/` section of the docs. Was not sure how much detail I should go into as far as instructions, but happy to expand on things if preferred
=> Improving connectivity page added

docs/mine/connectivity.md
Solves #188 
Also addresses comments left in original page merger PR
=> Feedback adjustments, connectivity page

docs/mine/spacerace.md
- Fix calibration link typo
- Add more info & links to "how to join" section
- Add link to calibration dashboard
@har00ga if this looks good to you, please merge. Thanks!
=> Followup updates to spacerace.md

docs/mine/spacerace.md
Add a couple of program FAQs from #space-race questions.
=> Add some FAQs

docs/.vuepress/config.js
Cleanup the sidebar navigation for Build including the new tutorials.
=> fix: navigation cleanup

docs/mine/connectivity.md
- Add troubleshooting section, copied from @daviddias's doc and adding the new connectivity checker tool.
=> Add troubleshooting section

docs/mine/connectivity.md
This PR adds a video link to the intro section of the improving connectivity page
=> Video link added

docs/mine/spacerace.md
Based on @magik6k's notes here: https://hastebin.com/qekumopali.cpp 
@Kubuxu - it would be really great if you could add a "how to change default message gas prices" // "how to change message selection logic" FAQ here as well
=> add docs on how to change deal acceptance logic

docs/how-to/networks.md
- Describes new faucet behavior
=> New faucet behavior

docs/.vuepress/config.js, docs/mine/connectivity.md, docs/mine/lotus-seal-worker.md, docs/mine/mining-troubleshooting.md, docs/mine/setting-a-static-port.md, docs/mine/storage-mining.md
Pretty much a copy and paste of the [Lotus mining docs](https://lotu.sh/en+mining).
Closes #250
=> Migrate Lotus mining docs.

docs/mine/spacerace.md
Adds to Space Race page - how to perform a sector upgrade, and how to know if it worked correctly.
=> Sector upgrade instructions

docs/mine/spacerace.md
Fix syntax for deal filtering example
=> Filter syntax

docs/how-to/networks.md, docs/mine/spacerace.md
This PR updates the Testnet description, timestamps, and details for Space Race.
* Updates faucet URL
* Updates bot wallet addresses & filter instructions
A follow-up PR will be required for branch & tag name once 0.5.1 is released.
=> Update Testnet details for Space Race

docs/mine/spacerace.md
Add wallet address for 4th (backup) dealbot
=> Add 4th wallet

docs/how-to/join-a-network.md
=> Upgrade instructions

docs/introduction/what-is-filecoin.md
Closes #295 
- added a paragraph summarizing what web3 is and why Filecoin needs it
=> Explain web3 and why Filecoin needs it

docs/how-to/store/tokens.md
It doesn't fit very well into the existing page, but I can't think of a better place to put it...fine for now.
=> Add section on replacing messages in mempool

docs/how-to/networks.md
Don't merge until 0.6.0 is live.
=> Update version number for testnet to 0.6.0

docs/how-to/networks.md
Update to 1 FIL and only once per Github account.
=> Update testnet faucet description

docs/store/lotus/import-data-from-ipfs.md
Closes #387 
- added documentation from Lotus
=> Add import data from ipfs guide from Lotus

docs/store/lotus/send-and-receive-fil.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/385
- Added content from Lotus docs about sending/receiving FIL
=> Add send-receive fil from lotus docs

docs/mine/lotus/replace-messages-in-mpool.md
Closes #395 
- added "Replace messages in the pool"
=> Add replace messages in the pool

docs/build/examples/network-inspector/step-1-start-lotus-devnet-and-go-ipfs.md, docs/build/examples/network-inspector/step-2-run-the-react-app.md
Closes #362
- updated docker image version
- update install command
=> Fix Network Inspector container crash issue

docs/build/examples/meme-marketplace/step-1-blockchain-and-contracts-setup.md
Closes #348 
- added context
- added troubleshooting section
=> Add context and a troubleshooting section

docs/mine/lotus/miner-configuration.md, docs/mine/lotus/sector-pledging.md
=> Updated recommended value for ExpectedSealDuration

docs/get-started/lotus/installation.md, docs/mine/lotus/miner-lifecycle.md, docs/mine/lotus/miner-setup.md
Putting together feedback from here and there.
=> Improve the section about re-starting the miner

docs/get-started/lotus/installation.md, docs/get-started/lotus/switch-networks.md
=> Be more clear about switching networks.

docs/get-started/lotus/upgrades.md
1-line change to clean up repeated link text.
=> Fix link text

docs/about-filecoin/filecoin-compared-to.md, docs/get-started/lotus/installation.md
There's a tiny formatting error that was causing some funky stuff to happen to the Lotus install docs. This PR fixes that error.
=> Fixes warning formatting in lotus install.

docs/build/lotus/api-token-generation.md
Tokens are not generated, lotus always returns the same.
=> Generating new tokens -> obtaining tokens

docs/get-started/lotus/installation.md
Also add reference to non-pruned snapshots, as they may be useful for some.
=> Installation - HTTP-fetch of snapshots

docs/store/lotus/retrieve-data.md
Since we use the find command first to find miners.
=> Add --miner to retrieve command

docs/.vuepress/config.js, docs/.vuepress/theme/components/Home.vue, docs/mine/README.md, docs/mine/hardware-requirements.md, docs/mine/mining-architectures.md
This PR increases the context around setting up a Filecoin mining operation.
The hardware requirements page has been reworked, explaining a bit better how
the requirements apply and providing not only general but also specific
requirements for each of the mining operations that need to be performed
(sealing phases etc).
A new "mining architecture" guide is added, with the PL v3 mining setup added
in it. It should hopefully include additional architectures from other parties
in the future.
=> Mining architectures. HW requirements revamp.

docs/about-filecoin/what-is-filecoin.md
Fixes grammar, spelling, and typos.
=> Editorizing "What is Filecoin".

docs/get-started/README.md
=> docs(get-started/README.md): Change punctuation

docs/get-started/lotus/installation.md
It said both quad-core and 8-core CPU.
Fixes #511
=> Fix requirements

docs/get-started/lotus/installation.md
Needed with https://github.com/filecoin-project/lotus/pull/4613
=> Add hwloc to lotus deps

docs/get-started/lotus/chain.md
This is still a temporary state of affairs. proper downloads are coming...
=> Add instruction for obtaining the sha256sum of a snapshot file

docs/mine/lotus/miner-setup.md
=> Updates miner walet addresses.

docs/get-started/lotus/installation.md
=> New deps added. Restructured deps list.

docs/get-started/lotus/installation.md
Made to fix #577, but there was nothing _to_ fix...
=> Removes TOC from Getting Started.

docs/get-started/lotus/installation.md
Updates deps Go from 1.14 to 1.15.5 for Lotus.
=> Updates Golang deps for Lotus.

docs/store/lotus/store-data.md
=> Recommends multiple storage deals.

docs/get-started/lotus/troubleshooting.md, docs/get-started/lotus/upgrades.md
This is bound to make people loose their keys
=> Don't instruct users to remove .lotus during upgrades

docs/get-started/lotus/configuration-and-advanced-usage.md
Add description of `SimultaneousTransfers` config option.
This should only be merged once https://github.com/filecoin-project/lotus/pull/4996 has been released.
=> Add SimultaneousTransfers config description

docs/get-started/lotus/installation.md
Some users were getting confused regarding which branch to use for which network. This PR clears that up a little bit.
=> Clarified branch/release tag issue.

docs/get-started/lotus/installation.md
=> Update CGO recommendation for MacOS too.

docs/mine/lotus/manage-storage-deals.md
Changes command to lotus-miner storage-deals...
=> Fix command: Offline storage deal

docs/get-started/lotus/installation.md
Tiny update for the latest release.
=> Links directly to release pages, not a tag,

docs/store/lotus/very-large-files.md
Fixes an outdated init issue within the docs, brought up by community members in Filecoin Slack.
=> Fixes outdated lotus-miner init.

docs/mine/lotus/README.md
=> Fixes grammar and typos.

docs/store/lotus/store-data.md
for checking CID storage status
=> Adding filecoin.tools info

docs/mine/lotus/message-pool.md
fixes https://github.com/filecoin-project/filecoin-docs/issues/657
=> shadow gas-limit flag in  message-pool.md

docs/reference/README.md
From https://github.com/filecoin-project/filecoin-docs/wiki
=> Big list of ecosystem tools and resources

docs/reference/README.md
A community repo maintained by members of CoinSummer.io and IPFSMain
=> Adding link to Filecoin 资源分享目录

docs/mine/lotus/miner-configuration.md
fixes https://github.com/filecoin-project/filecoin-docs/issues/683
=> Update miner-configuration.md - https://github.com/filecoin-project/filecoin-docs/issues/683

docs/mine/lotus/manage-storage-deals.md
Added how you can see deals waiting in your publish queue, and how you can force publish them,
=> Add "Deals that are pending publishing"-section

docs/build/hosted-powergate.md
The goal of this PR is to fix links and update CLI commands, while making a few small changes for readability.
cc: @andrewxhill
=> Hosted Powergate updates

docs/build/README.md
and => an
vailable => available
=> fix: minor typos

docs/build/examples/simple-pinning-service/step-3-connecting-powergate-to-app.md
The code snippet to create the database should go in `src/utils/database.js`
=> Fix filepath

docs/build/examples/meme-marketplace/textile-hub-buckets-and-erc721.md
Added link to the Start coding page for a better tutorial flow
=> Added link to the Start coding page

docs/mine/lotus/miner-configuration.md
There was some confusion about the indented behavior of `MaxWaitDealsSectors`, this should clear that up. Also updates some other things
=> Update miner configuration docs

docs/mine/mining-rewards.md
=> Fixes cl typo.

docs/mine/lotus/seal-workers.md
=> Memory -> RAM or Disk space.

docs/build/lotus/lotus-lite.md, docs/get-started/lotus/installation.md
=> Add M1 warning and lite-node install instructions.

docs/mine/lotus/miner-setup.md
Change the wallet-addresses from t3-addresses to f3
=> Change t-addresses to f-addresses

docs/community/README.md, docs/community/chat-and-discussion-forums.md
Replaces links to the deprecated Discuss forum with the GitHub discussions tab.
=> Changes Discuss to Discussion tab in GitHub.

docs/get-started/README.md, docs/get-started/lotus/send-and-receive-fil.md, docs/reference/README.md
Someone added Wallet Docs info to this page - removing
=> Removing someone's weird Wallet Docs add

docs/.vuepress/public/_redirects, docs/.vuepress/redirects, docs/get-started/lotus/installation.md
Redirects some [common inbound links that hit 404 pages](https://datastudio.google.com/reporting/62116ab2-5024-4e38-b35e-91b1a1e85806/page/pP5aB?utm_source=google-datastudio&utm_medium=email&utm_campaign=scheduled-report).
=> Adds redirects for common inbound links to hit 404 pages.

docs/get-started/lotus/installation.md
~/.bashrc Permission denied  change to source ~/.bashrc
=> source ~/.bashrc

docs/get-started/store-and-retrieve/store-data.md
similar to IPFS, these networks are find to use for encrypted data as long as you ack the security model: https://docs.ipfs.io/concepts/privacy/#encrypting-content-transported-via-ipfs
Maybe should be a warning instead of a "danger"?
=> Update store-data.md to correct warning

docs/get-started/README.md
=> Adds call out to Lotus API methods.

docs/build/lotus/lotus-lite.md
=> Updates M1 install instructions.

docs/get-started/lotus/switch-networks.md
=> Adds steps to change network properly.

docs/store/filecoin-plus.md
Merge upon network v13 upgrade
=> update filplus docs for network 13 upgrade

docs/get-started/lotus/installation.md
These are pretty new!
Watch to make sure https://snapcraft.io/lotus-filecoin looks right and https://github.com/filecoin-project/lotus/pull/6388 is merged before adding this to the docs.
=> Add steps for installing Lotus using AppImages.

docs/mine/lotus/miner-configuration.md
Added sealing configuration docs, missing fee sections.
=> Update miner configuration for hyperdrive

docs/reference/README.md
Update README.md to include [filecoin-js-signer](https://github.com/blitslabs/filecoin-js-signer) (a pure Typescript signing library),  and [Blits Wallet](https://blits.net), a mobile wallet supporting Filecoin
=> Update README.md to include new signing library and mobile wallet.

docs/community/contribute/ways-to-contribute.md
This PR is a one-line deletion.
=> Remove reference to shipyard (archived)

docs/get-started/store-and-retrieve/retrieve-data.md
Add a short intro section to the FFF tutorial for re-starting the `lotus daemon`.
=> Readds start lotus daemon command.

docs/get-started/README.md
Clarifies that the standard Lotus install is for folks who want a fully-featured deployment of Lotus.
=> Adds call out to a fully-featured node.

docs/mine/lotus/miner-setup.md, docs/mine/lotus/split-markets-miners.md
Related: https://github.com/filecoin-project/lotus/pull/6356
=> initial docs for splitting miner and markets service

docs/store/README.md
Correct the misspelled word rtoring to Storing.
=> [DOCS ISSUE] Page: Store data on Filecoin 

docs/get-started/lotus/installation.md
#925
I personally found it frustrating that the information on disk usage ("how big a disk do I need to make deals as a client") was not clear.  I believe this change provides the needed information.
I'm new to filecoin.  I understand an upcoming network change may change these numbers, but at least they set a norm of providing more information.
=> Clarify disk usage requirements

docs/about-filecoin/why-filecoin.md
This is not (yet) a thing.
Also moving up and slightly rewording the `Verifiable storage` section because IMO that is far and away the highlight of storing data on Filecoin.
=> Remove self-healing section

docs/mine/lotus/split-markets-miners.md
This PR is adding documentation on `Rollback` as a continuation of https://github.com/filecoin-project/filecoin-docs/pull/890
=> rollback docs for miner/markets split

docs/get-started/lotus/installation.md, docs/get-started/lotus/running-in-the-cloud.md
Removes a referral code that's found it's way into the docs.
=> Removes DO refcode.

docs/build/README.md, docs/build/estuary.md, docs/build/get-started.md, docs/get-started/README.md, docs/reference/README.md, docs/store/README.md, docs/store/estuary.md, package-lock.json
Reverts filecoin-project/filecoin-docs#976
Review was not properly addressed.
=> Revert "Feat/outbound linking to web3 storage"

docs/get-started/lotus/README.md
=> Fix typo on row 24

docs/get-started/store-and-retrieve/set-up.md
=> Branding updates

docs/get-started/store-and-retrieve/retrieve-data.md
Part of the _retrieve a file_ had the user downloading a 5gb file. This PR instructs the user to download a 66kb file instead :)
Closes #949
=> Uses a tiny file as an example download.

docs/about-filecoin/managing-assets.md
We were missing links for Glif and Trust wallet. This PR adds them.
=> Adds links to two wallets.

docs/build/signing-libraries.md
=> Updates Zondax link to point to the correct page.

docs/reference/README.md
=> Moves filwallet to 'Other wallets'.

docs/mine/lotus/miner-addresses.md
=> Fixes link.

docs/mine/lotus/miner-setup.md
=> Adds nvidia dep to miner install instructions.

docs/.vuepress/config.js, docs/get-started/lotus/backup-and-restore.md, docs/get-started/lotus/configuration-and-advanced-usage.md
=> Adds `lotus daemon` backup steps

docs/store/lotus/very-large-files.md
=> Removes 'calculate the datasize' section.

docs/get-started/lotus/installation.md
=> Adds updated deps to Fedora installation.

docs/README.md
I've tried to add the retrieval element here (question: Okay to include this even if retrieval markets are still somewhat WIP?) and I've tried to include the idea that users (questions: What do we call the agents that act on the Filecoin storage network? Is 'users' correct?) can decide how long their files should be available (incl. forever). I think this latter point is important in our positioning vs. other web3 storage solutions.
=> Update intro paragraph

docs/reference/README.md
=> Removes Filwallet link.

docs/.vuepress/config.js
=> Fixes sidebar nav not-showing issue.

docs/about-filecoin/faq.md
I deleted the second "storage."
=> Fixes storage storage

docs/reference/README.md
+ some tightening of descriptions
=> Adding new links for Storage Apps

docs/reference/README.md
Updating message signing tools section
=> Updating References

docs/about-filecoin/how-filecoin-works.md
Changed it in a link name to the page
=> Changed "mining" to "providing storage"

layouts/partials/head/script-header.html
Re-adds GA code since migration.
=> Adds GA code for analytics.

content/en/about-filecoin/ipfs-and-filecoin.md
=> Removes extra word.

content/en/about-filecoin/faq.md, content/en/about-filecoin/how-filecoin-works.md, content/en/about-filecoin/ipfs-and-filecoin.md, content/en/about-filecoin/what-is-filecoin/index.md
Found only a few typos in first few sections of Filecoin Basics.
However, FAQ had several forward looking answers for which I found updated info or acronym explanations in the spec, a blog, or updated Filecoin doc.
=> Reviews Filecoin Basics

content/en/storage-provider/how-providing-works.md
The last set of changes to this page were in the wrong project, so I deleted the wrong project from my machine (again) and re-cloned the correct project, which was up-to-date with main, except for these changes:
- Adds Level 2 and 3 Headings
- Changes links to relref format
=> Adds Heading 2&3 and relref to correct project

readme.md
Per feedback from legal Fixes #1251
=> Updated copyright info for README

content/en/about-filecoin/managing-assets/index.md
=> Adding MM link

content/en/reference/overview.md
=> Replaces miner with SP.

content/en/get-started/store-and-retrieve/set-up/index.md, content/en/get-started/store-and-retrieve/store-data/index.md
updates to 1.17.0
restores snap and appImage
tidies some of the instructions.
=> post 1.17.0 - snap, appImage, content tweaks

layouts/index.html
=> Grammar fix: it's → its.

layouts/partials/head/script-header.html
Adding this in to see if Plausible Analytics work for us within the context of Filecoin Docs.
=> Adds Plausible script.

content/en/get-started/overview/index.md
I corrected a typo on the 'Get Started' page
=> Corrected typo

content/en/build/powergate.md
Copied over info from the [Powergate Github Repo home page](https://github.com/textileio/powergate) on installing Go and setting PATH variables.
Closes https://github.com/filecoin-project/filecoin-docs/issues/1355
=> Add Golang requirement and how to set PATH vars

content/en/build/overview.md
This PR rewrites the initial section, per the [draft](https://docs.google.com/document/d/1er7ogbVN6G_4Wb3p8GRbsX3ZASaB6BuA-7tz-68STzc/edit#heading=h.4hr77riwkn7m).
It aims to help developers choose what level of integration they're interested in, rather than jumping directly to a laundry list of tooling.
There are several missing links to internal content, which should be updated once that content is published. Issue ___ tracks these todos.
=> Rewrite overview.md

content/en/build/storage-helpers.md
- Create storage-helpers.md
- Updates navigation
=> Add storage helpers section

content/en/build/overview.md
Adds missing links to /build/overview.md, per #1369
=> Add missing links to Build Overview

README.md
Adds videos for:
- Managing the top bar
- Moving a page and adding a redirect
=> Adds basic video guides

README.md
Fixes some very tiny grammatical issues within the readme.
=> Fixes some grammatical errors.

content/en/get-started/_index.md
walks you through instead of walks "your" through
=> Update _index.md with minor issue

content/en/reference/overview.md
Brave wallets has FIL support, as once mentioned in the filecoin blog
=> Add Brave Wallet to wallet list

content/en/get-started/store-and-retrieve/set-up/index.md
bzr is no longer a dependency as per this thread. 
https://filecoinproject.slack.com/archives/CP50PPW2X/p1664566751489689
=> update to 1.17.2 + remove bzr as a dependency

content/en/fvm/basics/faqs/index.md
Adds all the [FAQs from this forum post](https://github.com/filecoin-project/filecoin-docs/tree/update/fvm-faqs) into the docs.
=> Updates FAQs from forum post.

content/en/build/tools/powergate/index.md
Adds an alias for powergate based off IPFS 404ing link.
=> Adds redirect alias for Powergate.

content/en/about/basics/how-filecoin-works/index.md
Just some minor updates grammar and spelling wise to the _How Filecoin Works_ page.
=> Minor updates to "How Filecoin Works" page.

assets/scss/common/_dark.scss, assets/scss/components/_alerts.scss
Closes https://github.com/filecoin-project/filecoin-docs/issues/1508
=> Sets links to proper colour in light/dark mode.

assets/js/clipboard.js
Closes https://github.com/filecoin-project/filecoin-docs/issues/1522
=> Disables copy on second-code blocks.

content/en/about/contribute/grammar-and-formatting/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/963.
=> Clarifies FIL use-case. Fixes formatting.

content/en/about/basics/filecoin-faq/index.md, content/en/developers/introduction/filecoin-and-ipfs/index.md
Replication of https://github.com/filecoin-project/filecoin-docs/pull/1430.
=> Adds improved descriptions based on SEO.

assets/scss/common/_global.scss, assets/scss/common/_variables.scss
Closes https://github.com/filecoin-project/filecoin-docs/issues/1519.
=> Increases readability of lead text.

content/en/about/assets/fil-token/index.md, content/en/about/assets/wrapped-filecoin/index.md, content/en/about/basics/filecoin-compared-to/index.md, content/en/about/basics/how-filecoin-works/index.md, content/en/about/basics/what-is-filecoin/index.md, content/en/about/community/chat-and-discussion-forums/index.md, content/en/about/community/social-media/index.md, content/en/about/contribute/contribution-tutorial/index.md, content/en/about/contribute/grammar-and-formatting/index.md, content/en/about/contribute/ways-to-contribute/index.md, content/en/about/contribute/writing-guide/index.md, content/en/about/project/related-projects/index.md, content/en/about/project/the-filecoin-project/index.md, content/en/get-started/explore/explore-the-network/index.md, content/en/get-started/store-and-retrieve/introduction/index.md, content/en/get-started/store-and-retrieve/retrieve-data/index.md, content/en/get-started/store-and-retrieve/setup/index.md, content/en/get-started/store-and-retrieve/store-data/index.md, content/en/get-started/store-and-retrieve/troubleshooting/index.md, content/en/networks/overview/available-networks/index.md, content/en/networks/overview/network-performance/index.md
Adds nice fancy lead text for all the visible pages in docs.
=> Adds lead to all pages

README.md
Just adds a simple status tag for the website in the repo `README.md` file.
=> Adds a website status link to the repo `readme.md`.

content/en/about/basics/filecoin-faq/index.md, content/en/about/basics/what-is-filecoin/index.md, content/en/archive/archived-filecoin-backed-pinning-services/index.md, content/en/archive/archived-powergate/index.md, content/en/developers/introduction/overview/index.md, content/en/developers/reference/json-rpc/introduction/index.md, content/en/get-started/explore/explore-the-network/index.md, content/en/networks/overview/available-networks/index.md, content/en/networks/overview/network-performance/index.md, content/en/reference/reference/overview/index.md, content/en/storage-provider/basics/how-providing-storage-works/index.md, content/en/storage-provider/basics/overview/index.md, content/en/storage-provider/hardware/architectures/index.md, content/en/storage-provider/hardware/hardware-requirements/index.md, content/en/storage-provider/rewards/slashing/index.md, content/en/storage-provider/rewards/storage-provider-rewards/index.md, content/en/store/overview/start-storing/index.md, layouts/index.redirects
Closes https://github.com/filecoin-project/filecoin-docs/issues/1557
=> Adds alias redirects for issue 1557.

content/en/networks/overview/available-networks/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1566
=> Adds Hyperspace information to the Available networks list.

layouts/partials/head/seo.html
pretty self-explanatory. I think we may have a separate robots.txt problem but I'll discuss that in chat first.
=> removes stray robots directives fixing #1560

content/en/about/basics/introduction/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1582
=> Adds Intro to Filecoin piece.

content/en/about/basics/introduction/index.md
Added the following redirects for [/about/basics/introduction/](https://docs.filecoin.io/about/basics/introduction/):
```
- "/introduction"
- "/introduction-to-filecoin"
- "/intro-to-filecoin"
```
=> Adds redirects for Filecoin introduction.

content/en/developers/smart-contracts/about/blueprints/index.md
Changes 'perp' to 'perpetual'. Perp has other connotations.
=> Changes 'perp' to 'perpetual'.

content/en/about/basics/filecoin-compared-to/index.md, content/en/about/basics/what-is-filecoin/index.md, content/en/get-started/overview/get-started/index.md, content/en/storage-provider/basics/how-providing-storage-works/index.md, content/en/storage-provider/hardware/hardware-requirements/index.md, content/en/store/filecoin-plus/overview/index.md, content/en/store/overview/start-storing/index.md
Updating the description field and correcting a few errors.
=> SEO Metadata updates

content/en/developers/smart-contracts/how-tos/add-to-metamask/index.md
Chain ID is not pointing to the right ID
=> fix chain id number

assets/js/clipboard.js, content/en/developers/infrastructure/how-tos/_index.md, content/en/developers/infrastructure/how-tos/spin-up-a-lite-node/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1613
=> Spin up a lite-node and connect to hyperspace.

content/en/developers/smart-contracts/how-tos/use-a-faucet/index.md, content/en/developers/smart-contracts/quickstart/index.md
The faucet is offering 5 tFIL instead of 5000 tFIL.
=> Update faucet value

layouts/partials/header/header.html
Moves the searchbar over to the right.
=> Pushes searchbar to the right.

content/en/developers/infrastructure/block-explorers/index.md
=> Added 2 explorers

content/en/store/overview/start-storing/index.md
Adding Filebase to IPFS Pinning Services
=> Add Filebase

content/en/developers/reference/tools/index.md
Info in docs already and links are old and not evergreen
Closes https://github.com/filecoin-project/filecoin-docs/issues/1647
=> Remove FVM TO EVM section

archetypes/page/index.md, archetypes/sidebar/_index.md, archetypes/topbar/_index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1574.
=> Removes un-used items from archetype front-matter.

content/en/developers/infrastructure/networks/index.md
=> Recreate the deprecated networks list.

content/en/developers/infrastructure/how-tos/run-a-local-network/index.md, content/en/developers/infrastructure/how-tos/start-a-local-network/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1634
=> Adds local-devnet tutorial.

content/en/store/overview/start-storing/index.md
Adding context that Filebase will be adding Filecoin to its portfolio.
=> Editing Filebase description

content/en/intro/intro-to-filecoin/programming-on-filecoin/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1640
=> Fixes external links from intro to Filecoin.

content/en/intro/intro-to-filecoin/crypto-economics/index.md
Fixing typo useages -> usages on index page
=> Fixing typo: Update index.md

content/en/developers/infrastructure/how-tos/spin-up-a-lite-node/index.md
While running through this guide, I noticed a few nits. This PR fixes them.
=> Edits to Spin up a lite node guide

content/en/intro/intro-to-filecoin/blockchain/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1667
=> Adds description of consensus fault slashing.

content/en/developers/introduction/overview/index.md
I'm hoping we can make clear that they really are two separate networks, but that Filecoin also leverages the idea of content-addressing.
=> Better distinction between IPFS + Filecoin

content/en/developers/storage-helpers/how-tos/blockchain-integration/index.md, content/en/developers/storage-helpers/how-tos/data-encryption/index.md, content/en/developers/storage-helpers/how-tos/permissions-and-access-control/index.md, content/en/developers/storage-helpers/how-tos/retrieve-data/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1652
=> Adds the Lassie tutorial.

content/en/storage-provider/architecture/sealing-as-a-service/index.md, content/en/storage-provider/architecture/sealing-pipeline/index.md, content/en/storage-provider/architecture/sealing-rate/index.md
Small changes like capitalisation of Piece and suggested a tool tip.
=> Sealing pipeline tweaks

content/en/_index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1738
=> Hardcodes meta description.

content/en/smart-contracts/fundamentals/what-is-the-fvm/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1700
=> Adds draft for 'What is FVM' page.

content/en/store/filecoin-plus/overview/index.md, layouts/shortcodes/tooltip.html
For smart contract developers that need datacap
=> added a small note on Smart Contracts

content/en/developers/smart-contracts/how-tos/future-proof/index.md
Addresses [ issue 1666](https://github.com/filecoin-project/filecoin-docs/issues/1666).
Created a new page under Developers -> Smart Contracts -> How Tos based off of https://github.com/filecoin-project/testnet-hyperspace/issues/9
https://bafybeigkiflpaabs5jwrcwk4uonkp57eezj4wuovouxe7ih47ehjibx46y.on.fleek.co/developers/smart-contracts/how-tos/future-proof/
=> Issue 1666 - future proofing smart contracts

content/en/developers/infrastructure/networks/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1627
=> Adds further hyperspace info to Networks list.

layouts/shortcodes/tooltip.html
Adds tooltip hint for 'nonce'.
=> Adds tooltip hint for 'nonce'.

content/en/developers/smart-contracts/concepts/actors-and-contracts/index.md, content/en/reference/reference/glossary/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1547
=> Issue 1547 - Explain what actors and contracts are

content/en/developers/smart-contracts/how-tos/call-built-in-actor/index.md
Creates `content/en/developers/smart-contracts/how-tos/call-built-in-actor/index.md` to address https://github.com/filecoin-project/filecoin-docs/issues/1561
=> Issue 1561 - How to call a built-in actor

content/en/smart-contracts/developing-contracts/foundry/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1713
=> Adds foundry tutorial.

content/en/smart-contracts/wallets/fil-to-zero-x/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1791
I used https://docs.google.com/document/d/1kQRkQfxj2AN2QjC9Yssgtz1XekCYZvFbqewj71GSQrE as the foundation for this. Didn't include screenshots, because screenshots tend to get outdated... I can include them if we really want to though.
=> Issue 1791 - transfer Fil to 0x addrs

content/en/reference/json-rpc/eth/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1590
Receates now closed https://github.com/filecoin-project/filecoin-docs/pull/1751 but against the feat/docs-information-restructure branch
=> Issue 1590 Update JSON-RPC for Mainnet

content/en/storage-provider/basics/how-providing-storage-works/index.md
Fixes a typo in the Lotus install section
I just randomly noticed it
=> Fix a typo 

.vscode/settings.json, content/en/storage-provider/infrastructure/reference-architectures/index.md
I fiddled with Lightbox for a while, but it did seem unnecessarily complex. This implements it in the absolute simplest way possible - clicking on the link opens it fullsize (not a pop-up), but has the advantage that the back button works as normal, with an alert box call to action so people know it's clickable. I'll let @ivanka  recommend whether the alert should be above or below.
=> simple image breakout example

content/en/basics/the-blockchain/proofs/index.md, layouts/shortcodes/tooltip.html
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1804
Uses [tooltips](https://github.com/filecoin-project/filecoin-docs/blob/280c7f824ca15a544c6438f9f8135e1be624fe73/layouts/shortcodes/tooltip.html) that are added by this PR
=> Issue 1804 - Add conceptual info on proofs

content/en/smart-contracts/wallets/transfer-fil/index.md
=> Gemini has a deployment delay

content/en/networks/mainnet/rpcs/index.md
Added Chainstack public HTTPS and WebSocket endpoint, streamlined WebSocket terminology.
=> Added public Chainstack endpoint

.github/ISSUE_TEMPLATE/issue-ticket.yml
According to the GH docs, this PR should create a friendly issue template form thing like
=> Creates issue template

content/en/basics/assets/get-fil/index.md, content/en/basics/assets/the-fil-token/index.md, content/en/basics/assets/wallets/index.md
Adds in content that was originally added in #1788 but went missing somehow.
=> Re-adds content from previous PR 1788.

content/en/smart-contracts/fundamentals/roadmap/index.md
=> chore: update FVM roadmap

content/en/networks/mainnet/add-to-metamask/index.md
- Remove a stray mention to hyperspace from this page
- Update language (this is a configuration, not an integration)
=> Update Metamask <> FIL instructions

content/en/networks/hyperspace/rpcs/index.md, content/en/networks/mainnet/rpcs/index.md, content/en/nodes/node-providers/ankr/index.md, content/en/nodes/node-providers/chainstack/index.md, content/en/nodes/node-providers/glif/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1852
=> Updates RPC call examples.

content/en/storage-provider/architecture/Lotus-components/index.md, content/en/storage-provider/architecture/sealing-pipeline/index.md, content/en/storage-provider/architecture/sealing-rate/index.md, content/en/storage-provider/filecoin-deals/auxiliary-services/index.md, content/en/storage-provider/filecoin-deals/charging-for-data/index.md, content/en/storage-provider/filecoin-deals/filecoin-programs/index.md, content/en/storage-provider/filecoin-deals/return-on-investment/index.md, content/en/storage-provider/filecoin-deals/snap-deals/index.md, content/en/storage-provider/filecoin-deals/storage-deals/index.md, content/en/storage-provider/filecoin-deals/verified-deals/index.md, content/en/storage-provider/filecoin-economics/block-rewards/index.md, content/en/storage-provider/filecoin-economics/committed-capacity/index.md, content/en/storage-provider/filecoin-economics/fil-collateral/index.md, content/en/storage-provider/filecoin-economics/storage-proving/index.md, content/en/storage-provider/infrastructure/backup/index.md, content/en/storage-provider/infrastructure/network/index.md, content/en/storage-provider/infrastructure/reference-architectures/index.md, content/en/storage-provider/infrastructure/storage/index.md, content/en/storage-provider/skills/industry/index.md, content/en/storage-provider/skills/linux/index.md, content/en/storage-provider/skills/network/index.md, content/en/storage-provider/skills/sales/index.md, content/en/storage-provider/skills/security/index.md, content/en/storage-provider/skills/storage/index.md
Replaces https://github.com/filecoin-project/filecoin-docs/pull/1889
=> Add descriptions to each SP page.

content/en/basics/what-is-filecoin/crypto-economics/index.md
...even better: Fix it, but I don't know where it's supposed to go?
=> Remove the broken lnk

content/en/basics/what-is-filecoin/blockchain/index.md, content/en/basics/what-is-filecoin/crypto-economics/index.md, content/en/basics/what-is-filecoin/networks/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1882
=> Fixes borked links.

content/en/storage-provider/filecoin-deals/verified-deals/index.md
this page had a huge unsolved change in the code which leads to messy display.
=> Fixed unsolved change - urgent!

content/en/storage-provider/infrastructure/network/index.md, content/en/storage-provider/infrastructure/reference-architectures/index.md, content/en/storage-provider/infrastructure/storage/index.md, content/en/storage-provider/skills/security/index.md, content/en/storage-provider/skills/storage/index.md
and testing the process at the same time.
=> added content from Angelo's previous PR's

content/en/basics/assets/transfer-fil/index.md
* Updated ETH-style addresses in one other place
* Added a call-out asking readers to file a support issue with their exchange of choice
=> Include recommendation to file complaint

assets/scss/app.scss, assets/scss/components/_sp-calls-to-action.scss, content/en/storage-provider/basics/overview/index.md, layouts/shortcodes/sp-calls-to-action.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/1834
=> Creates new call-to-action for SPs.

content/en/basics/project-and-community/ways-to-contribute/index.md
Added a section on words that should not be use based on https://filecoinproject.slack.com/archives/C03Q117UBLM/p1678821501714589
=> Add list of terms to avoid and their alternatives

content/en/storage-provider/architecture/Lotus-components/index.md, content/en/storage-provider/architecture/sealing-rate/index.md, content/en/storage-provider/filecoin-deals/return-on-investment/index.md, layouts/shortcodes/tooltip.html
fixed code that was exposed in the text
=> Code issues on SP docs

content/en/networks/mainnet/add-to-metamask/index.md
=> link directly to the filecoin network page on chainlist

content/en/storage-provider/filecoin-deals/storage-deals/index.md, content/en/storage-provider/filecoin-deals/verified-deals/index.md, content/en/storage-provider/filecoin-economics/fil-collateral/index.md, content/en/storage-provider/filecoin-economics/storage-proving/index.md
Replaces https://github.com/filecoin-project/filecoin-docs/pull/1911
=> Adds clarifications from Trey.

content/en/smart-contracts/filecoin-evm-runtime/differences-with-ethereum/index.md, layouts/shortcodes/tooltip.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/1860
=> Adds deferred execution explanations.

content/en/storage-provider/basics/overview/index.md, content/en/storage-provider/filecoin-economics/committed-capacity/index.md, content/en/storage-provider/infrastructure/reference-architectures/index.md, content/en/storage-provider/skills/linux/index.md
A few updates to the Stef Notes comments.
=> Latest round of Stef Note corrections #1892

layouts/404.html, layouts/partials/head/script-header.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/1859
=> Adds script calls for 404 tracking.

content/en/smart-contracts/developing-contracts/best-practices/index.md
following up with this proposed change, in the erc-20 quickstart with a tutorial on this
=> add contract verification recommendation

content/en/basics/project-and-community/ways-to-contribute/index.md
- Added links for hackathons, accelerator 
- Swapped out some "we" (because who are "we") for more generic language
=> Some minor language tweaks to make more inclusive

content/en/basics/project-and-community/ways-to-contribute/index.md, content/en/reference/general/overview/index.md, content/en/smart-contracts/fundamentals/support/index.md, content/en/store/overview/start-storing/index.md
A few link updates and removals for docs based on the most recent SEO scan.
=> link updates for docs

content/en/basics/what-is-filecoin/networks/index.md, content/en/networks/spacenet/details/index.md, content/en/networks/spacenet/get-test-tokens/index.md, content/en/networks/spacenet/rpcs/index.md
Aligns the Spacenet pages with the format of the other network pages and updates information. We're keeping the genesis as a link for now but the rest should be fairly uniform.
=> Update Spacenet pages

content/en/nodes/implementations/venus/index.md
Also fixed some small spelling errors
=> Clarifies that Venus is built with Go, not Rust.

content/en/basics/project-and-community/ways-to-contribute/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1884
=> Adds grammar and formatting guide back in.

README.md
Literally just changes the README to include the new Thursday merge-process, and adds the priority table under the `Issues` section.
=> Adds merge process and priorities to README.

content/en/networks/mainnet/rpcs/index.md
Hello,
We are a Filecoin node provider NOWNodes.io.
Could you please add us to the node providers list?
=> Update list of node providers

content/en/networks/calibration/details/index.md, content/en/networks/mainnet/details/index.md
This PR contains snapshot links to be included from the Forest 🌲 node (maintained by ChainSafe).
=> Include Forest 🌲 snapshot links

content/en/smart-contracts/developing-contracts/verify-contracts/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/pull/1952#issuecomment-1551015334 by adding a basic guide on contract verification to Developing Contracts. Based off of https://gist.github.com/trruckerfling/54918b8331f6fa10ae27cedd6afd9680
=> Add contract verification guide to Developing Contracts

README.md
Just updates the screenshots for the README to show the Filecoin Docs homepage.
<picture align=center>
<source media="(prefers-color-scheme: dark)" srcset="https://ipfs.io/ipfs/QmWMouW8v6Rp9mAdmLJAtGD1nS4GfVUE51fYWE4ZCt7WWw">
<source media="(prefers-color-scheme: light)" srcset="https://ipfs.io/ipfs/QmPDzxTqqPKKwhEys2Ah9hRCowNDx2fbXGj8yKB7T5Qiby">
</picture>
=> Updates screenshots for README homepage.

README.md
adjusts linter instructions phrasing
=> Update linter instructions

content/en/smart-contracts/advanced/oracles/index.md, content/en/smart-contracts/advanced/wrapped-fil/index.md
=> Adds an Oracle page into `smart-contracts/advanced`.

content/en/smart-contracts/advanced/bridges/index.md
=> Adds an Briges page into `smart-contracts/advanced`.

layouts/index.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/2092
=> Re-adds Lotus blurb to front-page.

content/en/networks/calibration/details/index.md, content/en/networks/calibration/explorers/index.md, content/en/networks/calibration/rpcs/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2078
=> Improves content for Calibration devs.

content/en/reference/built-in-actors/filecoin-sol/index.md, content/en/reference/built-in-actors/overview/index.md, content/en/smart-contracts/developing-contracts/best-practices/index.md, content/en/smart-contracts/developing-contracts/call-built-in-actors/index.md, content/en/smart-contracts/developing-contracts/solidity-libraries/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2077
=> Moves Zondax references over to Filecoin Project GH org.

content/en/storage-provider/architecture/sp-automation/index.md, content/en/storage-provider/architecture/storage-provider-automation/index.md
renaming Lotus Automation into SP Automation
=> SP automation instead of Lotus automation

.spelling, content/en/basics/assets/transfer-fil/index.md, layouts/shortcodes/filecoin-transfer.html
Addresses https://github.com/filecoin-project/filecoin-docs/issues/2088
=> Creates a form to help users figureout which transfer method to use.

.spelling, content/en/basics/assets/transfer-fil/index.md, layouts/shortcodes/filecoin-transfer.html
Reverts filecoin-project/filecoin-docs#2065
=> Revert "Creates a form to help users figureout which transfer method to use."

content/en/smart-contracts/fundamentals/filecoin-evm-runtime/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2107
=> Fixes viewport issue with video.

config/_default/menus/menus.en.toml, layouts/partials/footer/footer.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/1927
=> Removes social links.

content/en/basics/the-blockchain/blocks-and-tipsets/index.md, layouts/shortcodes/tooltip.html
Closes https://github.com/filecoin-project/filecoin-docs/issues/1979
=> Adds explanation for blocktime.

assets/scss/common/_dark.scss
Closes https://github.com/filecoin-project/filecoin-docs/issues/2125
=> Fixes bottom nav buttons on dark mode.

.github/dependabot.yml
[@hyas/images](https://github.com/gethyas/images) is causing issues in later >3.0 version. This PR ignores any future changes to that package.
=> Ignores @hyas/images updates.

content/en/smart-contracts/fundamentals/the-filecoin-virtual-machine/index.md
Updated "The FVM" article, Google Doc version here: https://docs.google.com/document/d/1Fx3tgXA09_Wb4dPGqiSi6O6sZ8XvQuyLoMuuvc80g2o/edit
=> Update to "The FVM" article.

content/en/nodes/implementations/overview/index.md
Venus is written in Go
https://github.com/filecoin-project/venus
=> Fix Venus information

.spelling, content/en/networks/calibration/details/index.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2145
=> Adds SP listing section to Calibration details page.

content/en/smart-contracts/developing-contracts/client-contract-tutorial/index.md
- Provided placeholder to link to incoming Programmatic Storage doc
- Added Boost logs tooling into tutorial
=> Update client contract tutorial

basics/how-storage-works/storage-onramps.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2135
=> Removes Estuary from Storage Onboarding list.

.gitbook.yaml
Closes https://github.com/filecoin-project/filecoin-docs/issues/2192
=> Adds redirect for FilForwarder to Assets.

.gitbook.yaml
Closes https://github.com/filecoin-project/filecoin-docs/issues/2192
=> Updates redirects in gitbook.yaml.

.gitbook/assets/smart-contracts-developing-contracts-get-test-tokens-block-explorer.png:Zone.Identifier, .gitbook/assets/smart-contracts-developing-contracts-get-test-tokens-id-returned.png:Zone.Identifier, .gitbook/assets/smart-contracts-developing-contracts-get-test-tokens-send-funds.png:Zone.Identifier
Removes a bunch of those `Zone.Identifier` files that come with WSL2 these days.
=> Removes weird W11 files.

reference/built-in-actors/README.md, reference/exchanges/exchange-integration.md, reference/general/README.md, reference/general/tools.md, smart-contracts/developing-contracts/call-built-in-actors.md, smart-contracts/developing-contracts/filecoin.sol.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2138.
=> Removes references to Zondax.

basics/what-is-filecoin/blockchain.md, networks/calibration/rpcs.md, networks/mainnet/rpcs.md, smart-contracts/developing-contracts/verify-a-contract.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2203.
=> Replaces Chainlist with ChainID.

nodes/lite-nodes/spin-up-a-lite-node.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/1864
=> Simplify Rust installation for MacOS users.

smart-contracts/developing-contracts/client-contract-tutorial.md, smart-contracts/developing-contracts/hardhat.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2018.
=> Adds `.env` process to Client Contract Tutorial.

nodes/lite-nodes/spin-up-a-lite-node.md
Updated GO instructions and added reference links
=> Updated GO instructions

basics/assets/metamask-setup.md, networks/calibration/rpcs.md, networks/mainnet/rpcs.md, reference/general/README.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2225
=> Remove chainstack from RPC proviers.

.gitbook.yaml
Adding in redirects as directed by external SEO team. Duplicates removed, requesting review.
=> Adding redirects as needed. Duplicates removed.

.gitbook.yaml
Fixed the redirects on any page that needed a README file name.
=> New Branch with corrections to the yaml file

basics/assets/transfer-fil.md, basics/interplanetary-consensus.md, builder-cookbook/data-storage/retrieve-data.md, reference/general/README.md, reference/json-rpc/README.md
We had a bunch of broken links.
=> fix all broken links

storage-providers/filecoin-deals/filecoin-programs.md
Working on adding Github, doc, and Slack visual badges and linking them to appropriate sources.
See also: [Adding Sparkle to Social Coding: An Empirical Study of
Repository Badges in the npm Ecosystem](https://cmustrudel.github.io/papers/icse18badges.pdf)
=> Refresh filecoin-programs doc

basics/how-storage-works/filecoin-plus.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2264
=> Add datacapstats.io to Fil+ info

basics/how-storage-works/filecoin-plus.md, basics/the-blockchain/drand.md, reference/general/README.md
Fixed issues highlighted here: https://miro.com/app/board/uXjVK7faXbk=/
=> Fix filplus from dogfooding

basics/assets/the-fil-token.md
=> case correction

storage-providers/filecoin-deals/filecoin-programs.md
Some how the last badge styling fix didn't make it. Here I address that and additionally remove the linked headings of two former programs and include the URLs within parens.
=> Badges fix #2252

WELCOME.md, basics/assets/metamask-setup.md, storage-providers/filecoin-deals/filecoin-programs.md
9 months after the date in the message... I will also get the legacy site and DNS removed.
=> remove old legacy docs deprecation message

basics/how-storage-works/filecoin-plus.md, basics/project-and-community/filecoin-faqs.md, basics/the-blockchain/actors.md, basics/what-is-filecoin/storage-market.md, reference/built-in-actors/README.md, reference/general/README.md, smart-contracts/developing-contracts/filecoin.sol.md, storage-providers/filecoin-deals/filecoin-programs.md, storage-providers/filecoin-deals/snap-deals.md, storage-providers/filecoin-deals/verified-deals.md
Fixes references to notaries and "FIL+".
=> Fil plus deprecated links

networks/mainnet/rpcs.md
Reverts filecoin-project/filecoin-docs#2310
links to broken https://filecoin.getblock.io - backing out
=> Revert "Update rpcs.md"

basics/how-storage-works/filecoin-plus.md
Corrected a typo in "verified" previously misspelled as "verfied".
=> Fix typo in "verified"

networks/calibration/explorers.md
It actually exists, but it hard to find it as it is not stated in the docs, while stated on the mainnet...
=> Add Filecoin Testnet explorer to the list

SUMMARY.md, smart-contracts/advanced/aggregated-deal-making.md
Add `Contract automation` and `Relay` file to SUMMARY.md
[Related to this issue ](https://github.com/filecoin-project/filecoin-docs/pull/2324).
=> Add file links to Table Of Contents

networks/mainnet/explorers.md
Link checker on #2347 showed this as broken.
=> Fix Filfox link in explorers

basics/what-is-filecoin/networks.md, networks/calibration/README.md, networks/mainnet/README.md
Added Forest Explorer faucets - both calibnet and mainnet.
=> docs: add forest-explorer faucets

basics/project-and-community/filecoin-faqs.md
update with minor typo at the bottom of the [Filecoin FAQs](https://docs.filecoin.io/basics/project-and-community/filecoin-faqs) page.
=> docs: Update filecoin-faqs.md
