- docs/.vuepress/config.js
- docs/project/README.md
- docs/project/history.md
- Removes history section (from sidebar, section readme, and markdown stub)
- Swap position of Specification & Roadmap sections, because the Spec link works a bit better as overview.
- Tiny nit: Remove "s" from end of "Specification" link.
With these edits, I believe the Project section is ready to publish. Please mention if anything else is needed.
> Project section updates

- docs/.vuepress/config.js
Setting up our Filecoin docs Algolia DocSearch instance (was previously using IPFS search terms, will now crawl our site every 24 hours)
> update Algolia API key

- docs/how-to/build-interacting-with-the-network.md
- Adds lotus devnet link to "Local devnet" section.
- Moves "Filecoin Node Hosting" link to "Remote nodes" section
- Clean up TODOs and placeholder text
> Clarify localnet/devnet info

- docs/.vuepress/theme/components/Home.vue
This PR updates the homepage width to be consistent with other pages, including shrinking the background image to maintain a similar effect. It also fixes breakpoints so the grid boxes don't get excessively narrow when shrinking the screen. 
New homepage design on desktop: 
As compared to a normal page on desktop: 
New homepage design on mobile: 
On tablet: 
Pair programmed with @zebateira
> match width of homepage content to other pages

- docs/.vuepress/public/_redirects
HOLD to merge once the go-filecoin-tutorial is hosted at go.filecoin.io.
> ON HOLD: Update redirect URL for go-filecoin-tutorial

- docs/project/README.md
It's more updated. research.filecoin.io makes sense as Filecoin should be independent of PL, but it isn't recently updated.
> Adding info about CryptoLab to Research section

- docs/.vuepress/theme/components/Home.vue
Adds the IPFS and FIlecoin page to the introduction square on the lander
> Add IPFS & Filecoin page

- docs/how-to/build-interacting-with-the-network.md
(Ref. #79)
This PR adds a new section on the  "Interacting with the Network" page for setting up the new live devnet, and provides some miners for users to initially choose from.
> Add devnet connection instructions 

- docs/community/contribute/grammar-formatting-and-style.md
The existing description said to follow each list with a comma, when it should really be each item in the list, except for the last item.
> Update Oxford comma description

- README.md
Noticed many new contributors, so calling out that config.js does not automatically populate the homepage.
> Add instructions for featuring items on homepage

- docs/.vuepress/config.js
- docs/build/README.md
- docs/build/core-products/protocol-implementations.md
- docs/build/examples/sample-architectures.md
- docs/community/README.md
- docs/community/contribute/contribution-tutorial.md
- docs/community/contribute/grammar-formatting-and-style.md
- docs/community/contribute/ways-to-contribute.md
- docs/community/contribute/writing-guide.md
- docs/how-to/store/large-files.md
- docs/how-to/store/prepare-data.md
- docs/mine/mining.md
- docs/project/README.md
- package-lock.json
- package.json
> feat: automate checks for 404 links

- CONTRIBUTING.md
- docs/README.md
- docs/build/README.md
- docs/build/core-products/filecoin-backed-pinning-services.md
- docs/build/core-products/powergate.md
- docs/build/core-products/protocol-implementations.md
- docs/build/examples/meme-marketplace/overview.md
- docs/build/examples/sample-architectures.md
- docs/build/examples/simple-pinning-service/overview.md
- docs/community/README.md
- docs/community/contribute/contribution-tutorial.md
- docs/community/contribute/grammar-formatting-and-style.md
- docs/community/contribute/ways-to-contribute.md
- docs/community/contribute/writing-guide.md
- docs/how-to/README.md
- docs/how-to/install-filecoin.md
- docs/how-to/store/large-files.md
- docs/how-to/store/prepare-data.md
- docs/introduction/README.md
- docs/introduction/new-to-web3.md
- docs/introduction/why-filecoin.md
- docs/project/README.md
- docs/reference/README.md
This PR fixes routing issues for relative paths and sets up links correctly so you can navigate the documentation via the GitHub UI.
**Note for contributors**: It's recommended to [append the filename and extension](https://vuepress.vuejs.org/guide/markdown.html#internal-links) to all links to enable these to resolve correctly in both contexts.
related: #117
> fix: internal links

- docs/build/start-building/interacting-with-the-network.md
Stats dashboard for the nerpa network is online.
https://stats.nerpa.fildev.network/
> Update to add Nerpa Devnet stats dashboard

- docs/how-to/store/prepare-data.md
As far as I am aware, the only supported sector sizes now are 32GiB and 64GiB.
> update: supported sector sizes

- docs/.vuepress/config.js
setup medium-zoom correctly to stop images outside of the content area expanding.
ref: #136 #131
> fix: medium-zoom config

- docs/project/related-projects.md
Edit to link directly to a filtered list of Filecoin on content. I'm okay with matching the text to the real link but it gets pretty bulky so I've currently only displayed the URL for the main website while linking to the Filecoin course.
> Update link to ProtoSchool in Related Projects

- docs/.vuepress/config.js
- docs/.vuepress/theme/components/Home.vue
- docs/how-to/networks.md
- Moves Networks info out of Build section & to project level, so that Miners can also find it
- Updates sidebar & homepage links
- Adds top-level table to compare networks.
- Reorganizes each network's details with tables (feedback especially welcome here).
Questions for reviewers
- A main goal of this PR is to improve the overview of all networks, and make it very easy for people to pick the right one for them. Is that achieved? Any improvements to suggest?
- Are each network's details very clear & findable? Any improvements to suggest?
- Do the general "connection instructions" work? Another option is to revert to individual instructions (with branch/tag name pasted in for each), but I partly wanted to reinforce that all the steps for joining any network is basically the same. …
> Move & restructure Networks page

- docs/mine/spacerace.md
There was a rouge asterisk `*` floating about. Asterisk can denote a _bullet-point_, so VuePress was translating it into a `<li>`. Doesn't do that no more. Also fixed grammar and spelling issues.
> Fixes formatting & grammar/spell check.

- docs/.vuepress/public/_redirects
- docs/.vuepress/theme/layouts/404.vue
This implements the first version of a custom 404 page, inviting the user to return home or try search to complete their request.
An event for the error is triggered so we can monitor inbound 404 issues and attempt to fix them with redirects or content updates.   
fixes: #175
> feat: add custom 404 page

- docs/mine/connectivity.md
Due to the fact that the port number of the miner will be put on chain by the `set-addrs` call, it is ill-advised to use UPnP as it will potentially provide a new port if the process is restarted. This was my mistake as I suggested this change before I knew about putting the address on chain.
> Remove upnp section

- docs/mine/connectivity.md
This PR aims to add a troubleshooting table with common error messages, explanations, and recommended fixes. @har00ga can you take this over and land it today?
Please also add these errors:
- ClientQueryAsk failed : failed to open stream to miner: dial backoff
- ClientQueryAsk failed : failed to open stream to miner: failed to dial
- ClientQueryAsk failed : failed to open stream to miner: routing: not found
- ClientQueryAsk failed : failed to read ask response: stream reset
- {"code":1,"message":"cannot make retrieval deal for zero bytes"}
@daviddias - If you could provide a head start on the info required here that would be super helpful.
If explanations or fix recos are still missing please chase it down in #fil-space-race-admin.
> add troubleshooting table

- docs/.vuepress/config.js
- docs/.vuepress/nav/en.js
- docs/.vuepress/theme/components/Breadcrumbs.vue
- docs/.vuepress/theme/components/Page.vue
- docs/.vuepress/theme/styles/header.styl
- docs/.vuepress/theme/styles/index.styl
- docs/.vuepress/theme/styles/sidebar.styl
- docs/README.md
- docs/mine/README.md
Non-breaking primary navigation refactor to prepare for the full documentation restructure.
New content will be added in a future PR along with redirects once we've identified which content will be migrated.
In this PR:
- New `<Breadcrumbs />` component to aid with contextual navigation, esp on mobile pages with the menu collapsed
- New primary navigation concept with sticky top sidebar positioning
- Multiple sidebars to reduce the navigation depth
- New hover actions on sidebar navigation to lower the distraction of the navigation on desktop
- Unified typography style for menu navigation tree
- Added collapsable indicator for sidebar group elements
TODO:
ref: #154 #193
> feat: documentation navigation refactor

- docs/.vuepress/theme/styles/sidebar.styl
🐛 fix for scrolling crop in firefox.
rel #239
> fix: sidebar menu crop in ff

- docs/.vuepress/theme/components/ScrollPatch.vue
For pages with very long indexes it is easy to lose your location in the tree, this feature ensures the display is synchronised as you scroll so you can easily follow the TOC 💫
🧪  This uses the experimental [`Element.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) API so it may now work in all browsers but will fallback to default behaviour in those cases.
> feat: auto-scroll sidebar active item into view

- docs/.vuepress/theme/components/Breadcrumbs.vue
- docs/.vuepress/theme/components/Home.vue
- docs/.vuepress/theme/components/Page.vue
- docs/.vuepress/theme/styles/palette.styl
🐛 fixes nav offset issues for hash items when breadcrumbs are visible.
cc: @mishmosh please verify this is the correct behaviour when have a moment, thanks 🙏 
fixes: #263
ref: #239
> fix: allow for hash link offsets with breadcrumbs

- docs/community/contribute/grammar-formatting-and-style.md
- docs/reference/glossary.md
Here's a draft that seeks to clarify the project's preferred usage of the terms "Filecoin", FIL, filecoin, etc. in the documentation for contributors. This addresses a small component of #215
> Add guidelines on Filecoin term usage to grammar/style guide

- docs/community/contribute/grammar-formatting-and-style.md
- docs/how-to/store/large-files.md
- docs/mine/connectivity.md
- docs/mine/lotus-seal-worker.md
- docs/mine/mining-troubleshooting.md
- docs/mine/storage-mining.md
The `lotus-storage-miner` command does not exist anymore and was renamed to `lotus-miner`.
> Replace all reference of lotus-storage-miner with lotus-miner

- docs/build/start-building/interacting-with-the-network.md
The contents of this page is shown in the sidebar, so the contents menu at the top isn't necessary.
> Removes the contents menu from this page.

- docs/community/README.md
- docs/mine/spacerace.md
- Fix 2 outdated links with new shortcut that includes join token: https://filecoin.io/slack
- Update first 2 reward tier sizes
> Update Slack join link & reward tiers

- docs/.vuepress/config.js
- docs/.vuepress/theme/components/Home.vue
- docs/build/start-building/deploy-your-application-to-the-filecoin-testnet.md
Guide to help users deploy their applications to testnet. Explains some of the particulars of storing data to testnet given that testnet miners are currently heads-down focused on Space Race.
> Slingshot guide

- docs/build/start-building/interacting-with-the-network.md
It looks like the link to the Powergate guide had a stray ".md" extension.
> Fix link to Powergate guide

- docs/store/lotus/upgrades.md
Closes #392
- added upgrade section from Lotus with steps to delete `~/.lotus` folder
> Add upgrade instructions

- docs/build/examples/simple-pinning-service/step-1-powergate-setup.md
- docs/build/examples/simple-pinning-service/step-2-react-app-setup.md
- docs/build/examples/simple-pinning-service/step-4-explore-pinning-service-app.md
- docs/build/examples/simple-pinning-service/step-5-shut-down-the-application.md
Closes #356 
- Step 1
- renamed `devnet` to `localnet`
- updated version
- Step 2
- added Metamask plugin in the requirements
- changed `npm install` to `npm ci` to preserve package versions
- Step 4
- fixed link to metamask
- Step 5
- updated version
> Update Simple Pinning Service documentation

- docs/community/contribute/grammar-formatting-and-style.md
Adds a tiny section in the contribution guidelines for how to use the `:::tip:::` and `:::warning:::` blocks. @hsanjuan you requested this like 2 weeks ago, but I forgot about it until now.
> Adds Custom containers to contribution guidelines.

- docs/get-started/lotus/installation.md
Cannot just warn that 0.7.1 is broken on intel. Previous steps already explains how to workaround it and what the issue is.
> Remove out-of-context warning about 0.7.1

- docs/.vuepress/public/_redirects
- docs/build/onboard-testnet.md
- docs/get-started/lotus/troubleshooting.md
- docs/mine/lotus/miner-lifecycle.md
Redirects to capture top inbound 404s since docs restructure. There is no referrer to fix upstream so a 301 should fix it for now.
> fix: inbound 404s

- docs/build/lotus/hosted-nodes.md
Addin info about hosted Glif nodes, overview of what's supported + request form + Slack channel for Qs and status updates
> Adding info about hosted Glif nodes

- docs/about-filecoin/how-filecoin-works.md
- docs/get-started/lotus/send-and-receive-fil.md
- docs/mine/lotus/message-pool.md
Documentation on gas and fees was in the message pool guide, but this is not
information that is specific to lotus, it actually belongs to the network.
This moves information and definitions about gas and fees to the
how-filecoin-works guide. It takes in some improvements from the Gas Fees blog
post and adds some more.
> Move gas documentation to how-filecoin-works

- docs/community/contribute/grammar-formatting-and-style.md
Use **L**otus when talking about the Filecoin implementation. Use **l**otus when talking about the executable binary. Also, always surround `lotus` commands with back ticks.
> Adds "Referencess to Lotus" section.

- docs/store/README.md
- docs/store/slate.md
- docs/store/starling.md
This tidies up the Starling getting started guide, and also fixes a few grammar, formatting, and spelling issues that were floating around the root pages in `/store`.
> Tidy up Starling guide, fix some grammar issues.

- docs/store/starling.md
Adds NodeJS version requirement. It was missed off [that other PR](https://github.com/filecoin-project/filecoin-docs/pull/529#pullrequestreview-519859657).
> Specifies which NodeJS version to use.

- docs/about-filecoin/faq.md
- docs/about-filecoin/how-filecoin-works.md
- docs/reference/glossary.md
This PR is:
1. Fixing reference from "Windowed PoSt" to "Window PoSt", which I believe is the correct one, and how call it throughout the rest of the http://docs.filecoin.io/ website.
2. Removing the abbreviation PoSt from Proof-of-Storage. PoSt always refers to Proof-of-Spacetime, where Proof-of-Storage is a general category, meaning something else.
> fix references to PoSt

- docs/mine/lotus/sector-pledging.md
1. Specify the default pledge time. The previous text made it sound like it was always 6 months.
2. Specify that replacement sectors need to expire after pledged sectors.
3. Specify that the sector will become inactive 24 hours after a new sector has been sealed.
> specify timelines in pledge/upgrade docs

- docs/mine/lotus/manage-storage-deals.md
- docs/mine/lotus/miner-configuration.md
@johnnymatthews @jnthnvctr so... this is ready for review but is also somewhat of a draft:
- I scaled back the lean on "storage-deal filtering" and extended things in the general doc on filtering.
- The functionality added back in https://github.com/filecoin-project/lotus/pull/2069 was mid-documented ( it only works with PieceCIDs ) and I'd argue we need to go further and remove it entirely: it is of little utility :( 
- I would personally find examples of the JSON that is being fed to the programs **very** useful, but am not sure where it would fit nicely. Examples of both can be seen here: https://github.com/Murmuration-Labs/bitscreen/tree/45a84483c5a369c6fe6db90723aee11909b33ab4/testdata
> Expand doc on deal-fitlering via external hooks

- docs/mine/lotus/manage-storage-deals.md
Confirming that storage-deal prices are in FIL not attoFIL
> Fixing typo that should have FIL not attoFIL as units

- docs/get-started/lotus/installation.md
Disregard the Lotus version. I am not sure this has been fixed, but I heard a recent report that suggests it hasn't. Users on Intel should preferably use this then.
> installation: suggest CGO_CFLAGS for "older" CPUs

- docs/mine/hardware-requirements.md
Mining is quite expensive right now, so the feasibility of this statement isn't 100% factual. It's also grammatically incorrect.
> Removes line that is currently not strickly true.

- docs/get-started/lotus/installation.md
Ensures `wget` is installed as dependency on Debian. It is required for Go install and is not installed by default.
> Install wget in Debian

- docs/.vuepress/config.js
VuePress v1.8 now has the ability to customise the page suffix fixing inbound routing without JS enabled 🎉 
fixes: #428
ref: #154
> feat: setup pageSuffix to remove .html links

- docs/store/lotus/very-large-files.md
the parameter <minerAddress> is not need in the command `lotus client commP <inputCarFilePath>`
> fix the doc of generating the piece CID

- docs/get-started/lotus/configuration-and-advanced-usage.md
Add missing section to config file example.
See:
https://github.com/filecoin-project/lotus/blob/0cb2f515493eeaa686433665052dc03df34159de/node/config/def.go#L26
https://github.com/filecoin-project/lotus/blob/0cb2f515493eeaa686433665052dc03df34159de/node/config/def.go#L129
https://github.com/filecoin-project/lotus/blob/0cb2f515493eeaa686433665052dc03df34159de/node/config/def.go#L160
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1608428571333300
> Add Fees section and DefaultMaxFee

- docs/about-filecoin/how-filecoin-works.md
Adds tiny intro to Actors, and a complete description of filecoin addresses, which can't really be explained without Actors.
Ported from https://observablehq.com/@protocol/filecoin-addresses
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: add explainer for filecoin addresses

- docs/mine/lotus/message-pool.md
the output of `lotus mpool pending --local` is extensive and most of a messages values are not relevant for daily operation. 
added command to reduce the output of the command to key message values
fixes https://github.com/filecoin-project/filecoin-docs/issues/663
> howto reduce mpool pendig --local output

- docs/mine/lotus/miner-setup.md
- docs/mine/lotus/seal-workers.md
Optimal `BELLMAN_CPU_UTILIZATION` values depend on hardware, but currently we suggest a specific value without explaining at all that this is the case.
This PR is adding a note suggesting to users to try different values to determine the best value for their hardware.
> note about the value of bellman env var

- docs/get-started/README.md
A Filecoin community user in Slack tried Filfox Wallet and got their funds stuck, it doesn't look security audited and not sure why it's linked from Filfox. We can mention that there are additional wallets when the updated References page PR is merged.
> Remove Filfox wallet

- docs/community/contribute/grammar-formatting-and-style.md
- docs/mine/lotus/seal-workers.md
Removes a few ` ```text ` blocks from markdown since `text` is not a supported syntax style.
> Removes `text codeblocks.

- docs/mine/lotus/connectivity.md
Corrects links for bootstrap peer lists; the generic (per branch?) bootstrappers.pi appears to have been removed.
> Minor: fix links for bootstrap lists

- docs/get-started/lotus/chain.md
When following the documentation the command below fails.
`lotus chain export --skip-old-msgs <filename>`
with the error
`ERROR: must pass recent stateroots along with skip-old-msgs`
This patch updates the example to also include the needed `-recent-stateroots` option.
> Using skip-old-msgs fails

- docs/get-started/lotus/chain.md
- docs/get-started/lotus/installation.md
Because snapshots are taken every hour, and it can take more then one hour to download it (currently it's about 21GB), the verification of the checksum fails. You should find and download the correct sha256sum at the moment of the download, not the current one. This modification fix that.
Also, this fix poses a stronger recommendation to verify the checksum in the "Install & Setup" section.
> Fixed problem with checksum verification

- README.md
- docs/about-filecoin/how-filecoin-works.md
We want to document more details on the BLS curves used in Filecoin which will assist people trying to integrate with the system.
The spec mentions the BLS curves in more depth, but doesn't mention the Big / Little Endian storage anywhere, which is what tripped us up in using standard BLS libraries.
Also including a minor spelling fix for the README.
> Note on BLS curves and big/little endianess

- docs/get-started/lotus/installation.md
Only a release tag is really needed for n00bs.
More advanced users can choose a branch if they want.
> Simplifying checkout instructions

- docs/build/examples/simple-pinning-service/powergate-lotus-go-ipfs-interactions.md
Replace deprecated link to https://lotu.sh/ with https://docs.filecoin.io/build/lotus/
> Update reference to Lotus documents

- docs/get-started/lotus/installation.md
Adds a little tip about `$PATH` for users installing Golang on Linux. I always end up jumping over to the Golang docs because I forget the suggested path, so thought I'd add it in here as a tip.
This PR also removes the _add `rust` to your path_ tip, because the Rust install script automatically does that.
> Adds a Golang path install tip.

- docs/.vuepress/config.js
- docs/get-started/lotus/installation.md
- docs/get-started/lotus/running-in-the-cloud.md
Add a detour in the "Lotus installation" page just in case someone might be interested in the easier cloud-based option (then, hand off to the nitty-gritty of local installation). Additionally, exposing the draft-ish "Running in the Cloud" article in nav and sprucing it up for prime-time.
> Add pointer to running Lotus in the cloud. Publish "Running in the Cloud".

- docs/.vuepress/config.js
- docs/build/lotus/lotus-lite.md
A Lotus lite-node is a tiny version of Lotus that doesn't contain any chain-data, and relies on a full-node to process chain-related transactions. Lite-nodes are useful for performing actions that do not require access to the Filecoin chain such as deal-making and transferring files.
> Add a page for Lotus lite-nodes.

- docs/get-started/README.md
- docs/reference/README.md
- docs/reference/glossary.md
This adds a section to the reference page on the types of addresses used by wallets, with a quick writeup on how to tell the difference between public key and ID addresses and a warning not to send to brand new ID addresses.
I also added a little context to the wallet section on the Getting Started page, which was a little bare.
@johnnymatthews I think I must need to be added to the filecoin-project org or something, since it wouldn't let me push to the main repo. At any rate, this should close https://github.com/filecoin-project/filecoin-docs/issues/816 (cc @autonome)
> add info about addresses to wallet reference & getting started

- docs/.vuepress/theme/components/Home.vue
PR #836 removed the Roadmap link from the homepage. This PR adds a link to the FIP GItHub repo in the Roadmap link's place.
> Adds FIP link to homepage.

- docs/reference/README.md
As an open source example of how to use the Filecoin Signing Tools library
> Reference - add Glif Wallet ref to Signing Tools

- docs/mine/how-mining-works.md
This adds a link to the protocols labs Filecoin tutorials as a
tip at the top of the page. This is a fix for [issue 831](https://github.com/filecoin-project/filecoin-docs/issues/831).
> Issue831 v2

- docs/.vuepress/config.js
#871 was missing changes to the config.js file. This PR adds the pages to the sidebar.
> Adds Estuary to sidebar.

- docs/mine/lotus/miner-configuration.md
The lotus-miner sectors batching commit command, was missing 'sectors'
> Fix typo in batching commit command

- README.md
- docs/build/get-started.md
- docs/build/lotus/go-json-rpc.md
- docs/community/contribute/contribution-tutorial.md
- docs/community/contribute/grammar-formatting-and-style.md
- docs/get-started/lotus/chain.md
- docs/get-started/lotus/installation.md
- docs/get-started/lotus/multisig.md
- docs/get-started/lotus/send-and-receive-fil.md
- docs/get-started/lotus/troubleshooting.md
- docs/mine/lotus/backup-and-restore.md
- docs/mine/lotus/benchmarks.md
- docs/mine/lotus/miner-addresses.md
- docs/mine/lotus/miner-lifecycle.md
- docs/store/lotus/import-data-from-ipfs.md
- docs/store/starling.md
We'd previous been using `bash` in a lot of the code blocks for syntax highlighting, but turns out that `bash` isn't a valid syntax block type. This PR changes all the ` ```bash ` instances to ` ```shell `.
> Changes `bash` to `shell` in code blocks. [ciskip]

- docs/reference/README.md
Proposed fix to https://github.com/filecoin-project/filecoin-docs/issues/915
> Fixed link https://stats.testnet.filecoin.io/ to mainnet

- docs/store/filecoin-plus.md
Since the lotus API is structured as v0 and v1, there is a link to the API documentation that is not working anymore.
> Fix a broken link in filecoin-plus

- docs/build/lotus/lotus-lite.md
We've been working on enabling Lotus Lite functionality and stuck for some time while trying to make it work with the Lotus token. It appeared that we need to have the `:` (colon) sign between the api token and the actual address, while this documentation may be misleading. Creating this PR to fix the issue.
> Fix the colon absence

- docs/build/lotus/go-json-rpc.md
Since https://github.com/filecoin-project/lotus/pull/5685 `apistruct` no longer exists.
> Remove the use of apistruct in go-jsonrpc example

- docs/.vuepress/nav/en.js
- docs/.vuepress/public/_redirects
- docs/.vuepress/theme/components/Home.vue
- docs/get-started/README.md
- docs/get-started/lotus/send-and-receive-fil.md
- docs/store/lotus/store-data.md
networks.filecoin.io redirects to network.filecoin.io (without the `s`). This PR just updates all those links so @filecorgi doesn't complain anymore.
> Changes 'networks.filecoin.io' to 'network.filecoin.io'.

- docs/about-filecoin/managing-assets.md
This warning _did_ exist at some point, but it's got lost somewhere. This PR adds a warning to the wallets section pointing out that unaudited wallets are potentially dangerous and should be used with caution.
> Adds missing warning about unauditied wallets.

- docs/mine/lotus/split-markets-miners.md
This PR is adding steps on how to `export/import` a backup with all markets-related metadata, so that users who upgraded to a multi-service architecture and accepted storage deals, can continue to retrieve those deals correctly in case they rollback to a monolith architecture.
> add notes regarding exporting/importing market data with lotus-shed

- docs/mine/lotus/split-markets-miners.md
This PR is updating docs, with respect to https://github.com/filecoin-project/lotus/pull/6936
We are also updating commands and instructions based on feedback from miners.
> update docs based on new PR with LOTUS_MARKETS_PATH

- docs/get-started/lotus/installation.md
Closes #894.
Also removes the reference to a _bug_ with older Intel and AMD CPUs.
> Adds steps to disable multi-sdr.

- docs/store/filecoin-plus.md
Switching from FIL+ to Fil+, miner to storage provider (aside from certain instances, where there are more dependencies like the Miner Registry)
> Update for branding copy changes

- docs/get-started/lotus/chain.md
Update `Get Started -> Lotus -> Chain Management` to add instruction on fast syncing for Testnet, both calibnet and Nerpa.
Since the snapshots for testnet are provided and maintained by voluntary community members, this link might need to be updated periodically.
> add snapshot instruction for Testnet

- docs/mine/lotus/miner-setup.md
- docs/mine/lotus/seal-workers.md
When `lotus-miner` CLI is trying to connect to a remote `lotus-miner` (split between multiple machines, or not), it doesn't have any local repos, but needs to know the location of the `markets-api`, so the user should explicitly specify it in `MARKETS_API_INFO`.
This is an edge case, when the machine on which `lotus-miner` CLI client command is run has no repos, but given the fallback repo locations, it still tries to read `~/.lotusminer` for the API endpoint in case `MARKETS_API_INFO` is not specified.
> add MARKETS_API_INFO env var

- docs/mine/lotus/dagstore.md
Add a note about downgrading to Lotus versions that cause the dagstore feature set to be lost.
Fixes https://github.com/filecoin-project/lotus/issues/7116.
> docs(dagstore): add lotus rollback guidance to version prior to the dagstore

- docs/mine/lotus/miner-addresses.md
In PR #990, I deleted what I thought was a duplicate line. However, it turns out that it's not a duplicate command, but it does look very similar. Having both commands on separate lines might cause users, like myself, to assume it's a duplicate and just run the top line. Adding the 2nd part of the command with `&&` should mitigate this potential issue.
> Re-adds deleted line to `actor set-owner` command.

- docs/build/signing-libraries.md
Add a JS signing libirary to Build section, it was listed in reference already. And the team is using it for one of their loan project.
> Adding filecoin-js-siger to "Build->Signing libraries"

- docs/mine/lotus/message-pool.md
- docs/mine/lotus/miner-addresses.md
- docs/mine/lotus/miner-configuration.md
- docs/mine/lotus/sector-pledging.md
- docs/mine/lotus/split-markets-miners.md
Doc for 1.11.2. modify format with VSCode Markdownlint. and update some content
> Doc for 1.11.2

- docs/get-started/lotus/installation.md
wrong kind of quotes means that $PATH got expanded before being added to the bashrc... not good
> installation.md adding-go-to-path command was broken

- docs/README.md
- docs/build/README.md
- docs/get-started/README.md
- docs/mine/README.md
- docs/store/README.md
This PR adds simple callouts to lotus.filecoin.io throughout docs.filecoin.io. The callouts are mostly on the indexes of each section.
> Add callout to Lotus docs.

- docs/.vuepress/config.js
- package-lock.json
- package.json
Adds the [default VuePress search](https://vuepress.vuejs.org/plugin/official/plugin-search.html#usage) behaviour into the site. This replaces Algolia's Docsearch tool.
> Reverts back to original VuePress search.

- docs/.vuepress/config.js
- docs/project/README.md
Add community roadmap links to Filecoin Docs, replacing the instagantt link last updated in 2020.
cc @cwaring (thank you for the nudge!) @kaitlin-beegle
> update roadmap links

- docs/storage-provider/storage-provider-architectures.md
Proposal for removing the Protocol Labs example architecture until we get something better in place.
The hardware listed here is severely under-specced (espescially on RAM), and creates confusion for potential new storage providers.
> Remove Protocol Labs example hardware

- content/en/about-filecoin/managing-assets/index.md
Adds link to Lotus node setup for Filecoin
Tell users we don't support any of these wallets.
Recommends that they use a wallet that comes with hardware-wallet integration.
Alphabetize the list of wallets.
Adds a small section telling wallet creators how they can add their wallet to this list
> Adds "don't support," links, & new section

- content/en/about-filecoin/chat-and-discussion-forums.md
- content/en/about-filecoin/filecoin-compared-to.md
- content/en/about-filecoin/how-filecoin-works.md
- content/en/about-filecoin/ipfs-and-filecoin.md
- content/en/about-filecoin/managing-assets/index.md
- content/en/build/get-started.md
- content/en/build/get-started/index.md
- content/en/reference/exchanges.md
- content/en/storage-provider/how-providing-works.md
- content/en/storage-provider/how-providing-works/index.md
- Found and corrected some instances of Filecoin used where FIL should have been used.
- The [Grammar  & Formatting guide](https://docs.filecoin.io/about-filecoin/grammar-formatting-and-style/#references-to-filecoin) is already very specific and clear about this.
- As I was doing it, I found that there are two files with the same text, except one was older: index.md under storage provider and storage-provider.md. I got the out-of-date one up to date. Should one of these be removed?
> Fixes FIL for crypto & Filecoin for network/protocol

- content/en/get-started/overview/index.md
There's a link from filecoin.io that's trying to go to `/how-to/install-filecoin`, which doesn't actually exist. This PR points that URL to the Get Started section.
> Adds redirect to help filecoin.io not freak out.

- content/en/storage-provider/how-providing-works.md
- content/en/storage-provider/how-providing-works/index.md
While watching Launchpad videos, I thought I had missed "Penalties," but it turns out that they are part of Slashing. While in there I updated a couple things that tightens up the organization of the page:
- "Responsibilities" would be better than "Requirements."
- zk-Snarks is really part of Proofs, so I put them together.
- Some of the links to ProtoSchool were not the right or best link.
- Retrieval was stuck in the middle of Storage responsibilities.
But the weirdest thing is that there are two versions of the same file. I think index.md is the one that we are using and how-providing-works.md is not being used and should be deleted. Can you confirm? When I click on the _Edit this page in GitHub_ link, it shows that the page we're publishing is index.md
> Tightens organization; 2 pages with same content

- config/_default/params.toml
The copy buttons aren't working, for some reason. There's also a lot of console errors being spat out:
This PR disables the copy button next to code blocks. This is a temporary measure while we figure out why things aren't working. I have a feeling it's got something to do with the ElasticSearch function that got added recently, but we'll have to do a bit of digging. Either that, or there's some crazy dep that's causing things to break.
> Disables copy button.

- content/en/storage-provider/how-providing-works/index.md
Took a chance editing directly, since we just spent so much time correcting these.... Just removing a stray final parentheses.
> Removes extra final paren after "slashing" link

- build-directly-on-filecoin.md
- upcoming-features.md
Child of issue #1263
These three markdown files should be added under content/en/build section as part of structure for upcoming new content
> 3 new files for the new dev docs org structure

- content/en/get-started/overview/index.md
I have consulted Lotus team, Venus team, and Forest team regarding to the status of their implementation to recommend a new table update. Fuhon's information was confirmed by a Filecoin Technical Program Manager. 
The VM and VM Actors statuses now reflects the FVM project. A note is added regarding to Fuhon's deprecation and link to the repository is provided. 
Old Table: 
New table:
> Updated Filecoin Implementation Table

- content/en/storage-provider/how-providing-works/index.md
Issue #1329 
- Removes last sentence of first paragraph (Goes on too long about something we're leaving behind.)
- Makes opening sentence of paragraph two more conventional.
- Uses the word "responsibilities" instead of "requirements" to be in-line with headings below.
> Removes last sentence in first paragraph

- content/en/get-started/overview/index.md
- content/en/networks/overview.md
Adds Glif Explorer to resources section within `/networks/overview/`. Not sure if Glif Explorer would be considered a block explorer, but that's what it seemed like to me. If that's incorrect let me know and I will change it to a more accurate description. :)
> Add glif explorer to resources

- content/en/build/get-started/index.md
Remove trailing comma from JSON `body` in steps 2 and 3 of 'Validate an Address'
> Remove trailing commas from JSON within Getting Started Tutorial code snippets

- content/en/about-filecoin/chat-and-discussion-forums.md
Matrix changed from "communities" to "spaces", which changed the URL. This PR updates the link.
> Update Matrix link

- config/_default/params.toml
The copy button still has some conflicts with the search JS snippets. Removing the copy functionality until we can get around to fixing the search scripts. Closes https://github.com/filecoin-project/filecoin-docs/issues/1391
> Disables copy button again.

- content/en/get-started/store-and-retrieve/set-up/index.md
As it says. I'm not sure what happened here, and I don't have the time nor inclination to go diving into github to work it out.
> fixed 2 odd regressions in the lotus tutorial, updated links to 1.17.1

- content/en/reference/overview.md
It seems on main filecoin docs webpage the link to Glif nodes is broken. I found it when I was checking where there is info about CID Checker API out there, so I decided to add these two small fixes, please check ❤️
> Fix the link to the Glif nodes and add info about CID Checker API

- content/en/networks/overview.md
Some of the Slack links were pointing to archived channels. This PR updates the links to point to active channels.
> Updates Slack links.

- content/en/about-filecoin/wrapped-filecoin.md
- content/en/about-filecoin/wrapped-filecoin/index.md
Just a simple typo fix, Ethereum was spelled Etherium in a few places. :)
> typo: rewrite Etherium -> Ethereum

- content/en/get-started/resources.md
There was a link that was somehow caught up in a gitignore rule. This PR fixes that link so the site builds.
> Fixes link that was caught up in gitignore.

- content/en/fvm/how-tos/add-to-metamask/index.md
When we click on Wallaby testnet faucet the it leads to (https://docs.filecoin.io/fvm/how-tos/add-to-metamask/#use-the-wallaby-faucet) which leads to nothing.
So I updated the link to => (https://wallaby.network/#faucet)
> Error in Documentation

- content/en/build/get-building/overview/index.md
Two links just lead the user right back to this page. I'm removing them for now until we can decide where they _should_ go.
Closes https://github.com/filecoin-project/filecoin-docs/issues/1465
> Removes a couple of recursive links to this page.

- content/en/fvm/concepts/tipsets/index.md
Suggestion [taken from Slack](https://filecoinproject.slack.com/archives/C029MT4PQB1/p1670441237698649):
```plaintext
Filecoin => FEVM translation question:
I'm trying to work around some of the RPC bugs while they are being worked on. One approach I'm trying in order to retrieve logs is to query every block for logs and determine if they are logs I want.
Because I can't filter for new blocks, what I do is poll eth_blockNumber to get the current block number and if I see a new block number, I call eth_getLogs . But the behavior I'm seeing is I query block 5, I don't see any logs. And then once block 6 or 7 is reported, I query block 5 and the logs I expect are present.
So my question is, filecoin tipsets are not final even when the corresponding FEVM block number is reported by …
```
> Clarifies the finality of a tipset.

- README.md
Need to use `npm run start` to run a local server, not `build`.
> Changing `build` to `start` in local server instructions.

- content/en/fvm/basics/faqs/index.md
- content/en/fvm/reference/networks/index.md
The Factor8 team moved their Wallaby docs to a new location. This PR updates our outbound links so they don't 404.
> Updates Factor8 wallaby docs links.

- assets/scss/components/_alerts.scss
- config/_default/params.toml
Adds a simple top alert telling the user that they can view the legacy docs at legacy-docs.filecoin.io. The alert can be closed for this browser session.
> Adds legacy docs callout.

- content/en/networks/overview/available-networks/index.md
> fix: hyperspace link

- content/en/get-started/store-and-retrieve/introduction/index.md
- content/en/get-started/store-and-retrieve/setup/index.md
Snap and AppImage are too much effort to maintain for the amount of folks that use them, so remove them as valid install methods from the documentation.
> Deprecate Snap and AppImage

- content/en/developers/smart-contracts/concepts/data-access/index.md
We don't have any content in data-access right now. Setting to draft so it doesn't show up in prod site.
Closes https://github.com/filecoin-project/filecoin-docs/issues/1601
> Sets data access to draft.

- content/en/developers/infrastructure/networks/index.md
Edits the [docs.filecoin.io/developers/infrastructure/networks/](https://docs.filecoin.io/developers/infrastructure/networks/) page:
- Removes FVM releases section.
- Adds 64 GiB sections.
- Updates the Slack information.
> Removes FVM releases section, adds 64 sectors.

- assets/scss/common/_global.scss
Fixes a few issues reported in https://github.com/filecoin-project/filecoin-docs/issues/1563
- use `background-clip`in place of` -moz-background-clip` and `-webkit-background-clip` since the latter two don't seem to exist / be supported (???)
- use `-webkit-text-fill-color` instead of ` -moz-text-fill-color`
> Address 2 css issues flagged by FF console

- assets/scss/common/_global.scss
- layouts/docs/single.html
To address https://github.com/filecoin-project/filecoin-docs/issues/1648, set padding-bottom to 15px for the "on this page" dropdown that appears in mobile
Checkout the preview using the browser inspector to simulate the mobile view [here](https://bafybeihjnfr3x2cynje2vgbjolojeatvcug7sqackds2jkqb7equvwypzm.on.fleek.co/)
> Add 15px padding-bottom to mobile nav "on this page" dropdown

- content/en/developers/smart-contracts/hardhat/index.md
- content/en/reference/built-in-actors/overview/index.md
- content/en/reference/built-in-actors/protocol-api/_index.md
- content/en/reference/built-in-actors/protocol-api/account-actor/index.md
- content/en/reference/built-in-actors/protocol-api/datacap/index.md
- content/en/reference/built-in-actors/protocol-api/miner/index.md
- content/en/reference/built-in-actors/protocol-api/multisig/index.md
- content/en/reference/built-in-actors/protocol-api/storage-market-actor/index.md
- content/en/reference/built-in-actors/protocol-api/storage-power-actor/index.md
- content/en/reference/built-in-actors/protocol-api/verified-registry-actor/index.md
- content/en/reference/built-in-actors/solidity-api/_index.md
- content/en/reference/built-in-actors/solidity-api/filecoin-sol/index.md
- content/en/reference/external-apis/_index.md
- content/en/reference/external-apis/analytics/index.md
- content/en/reference/external-apis/chain/index.md
- content/en/reference/external-apis/deal-making/index.md
- content/en/reference/external-apis/indexing/index.md
- content/en/reference/external-apis/reputation/index.md
This PR:
- Creates a `/reference/built-in-actors` section.
- Moves the built-in actors API reference into `/reference/built-in-actors/protocol-api/`.
- Adds placeholder for `/reference/built-in-actors/solidity-api/filecoin-sol/`.
- Creates `/reference/external-apis` section with placeholders.
> Adds Protocol API section.

- content/en/intro/intro-to-filecoin/programming-on-filecoin/index.md
- layouts/shortcodes/releasing-on-mainnet.html
This PR adds a _this isn't available on mainnet yet but will be as on March 14th_ shortcode. This shortcode can be added to pages where the features aren't yet available on mainnet.
To use this shortcode enter `{{< releasing-on-mainnet >}}` within the markdown. For example:
```markdown
...
weight: 70
toc: true
---
{{< releasing-on-mainnet >}}
...
```
The benefit of using this shortcode is that we can quickly delete it after nv18 upgrade.
> Adds a 'release on mainnet' shortcode.

- content/en/developers/infrastructure/libraries/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1683
I used the info in https://github.com/filecoin-project/testnet-hyperspace#resources -> Filecoin Solidity libs. Based off that, looks like there's two Zondax libraries, Filecoin Solidity and FEVM Precompiles. Not sure if I misunderstood that
I should note that I am keeping descriptions intentionally short because it looks like both of these libraries are very much under development, so I'm just trying to give the reader the high level and then send them to the maintainers docs. Not sure if that fits the bill here, but that would be my recommendation 
*Blocker* 
The info on FEVM Precompiles is a bit hard to fill out based on https://github.com/Zondax/fevm-solidity-precompiles/tree/main/docs/fevm-solidity-precompiles... …
> Issue 1683 - Add Zondax libraries

- content/en/developers/smart-contracts/how-tos/get-test-tokens/index.md
Fix the spelling mistake in the lotus command for creating an f4 wallet.
> fix: get test tokens

- content/en/smart-contracts/filecoin-evm-runtime/differences-with-ethereum/index.md
This is in the "differences with Ethereum" section because, in Ethereum, contracts only ever have one address.
> fevm: document how the multiple 0x-style addresses interact

- config/_default/params.toml
It might be causing issues with caching. We also don't really need it.
> Disable instant page.

- content/en/reference/json-rpc/introduction/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1819
Removes Fuhon from list of nodes in /reference/json-rpc/introduction/
> Remove Fuhon in /reference/json-rpc/introduction/

- assets/scss/components/_buttons.scss
- layouts/shortcodes/button.html
Added a global button style so that when its used from an .md file , it would always use the same button style throughout the docs. 
example:
this way works too:
> Added global button style that matches the homepage style

- config/_default/menus/menus.en.toml
- layouts/partials/header/header.html
A bug in the current Filecoin docs causes the topbar items to _not_ be bolded when:
- The item contains an empty space.
- The item doesn't match the directory name.
- The item is a dropdown.
For example, _Storage providers_ is not bolded when in the `storage-provider` section:
This PR fixes this issue by:
- Hardcoding the names and directories of each topbar menu.
- Adding logic to add the `active` class on any topbar menu item, even if it's a dropdown.
This PR also changed the topbar item of *Smart contracts* to *Smart Contracts*.
This branch was initially started as a test to see if this was possible to fix. Turns out it was possible to fix, leading to the strange branch name.
> Keeps topbar items bolded, even when they're dropdowns.

- content/en/basics/what-is-filecoin/networks/index.md
The Calibration network faucet link is broken due to the lack of a closing parenthesis.
> fix(docs): missing closing parenthesis

- pre-commit-lint.sh
This PR troubleshoots the "Bad substitution" error that pre-commit.sh sometimes throws. 
Basically, it looks like I was trying to expand an array, which is not necessary, because the input files list is a list of strings, not an array.
> Patches pre commit script

- content/en/basics/interplanetary-consensus/ipc-agent/index.md
Hi, I followed the instruction here https://docs.filecoin.io/basics/interplanetary-consensus/ipc-agent/ to create an ipc subnet. But found some command in this doc is outdated.
> Fix outdated content, using the latest ipc-agent 

- content/en/basics/assets/metamask-setup/index.md
- content/en/smart-contracts/developing-contracts/foundry/index.md
- content/en/smart-contracts/developing-contracts/remix/index.md
- content/en/smart-contracts/fundamentals/FAQs/index.md
There were a few pages where we still had mentions of the Hyperspace testnet. It's been deprecated for a few weeks now. This PR removes those mentions of Hyperspace.
> Removes lingering mentions of Hyperspace.

- content/en/basics/assets/metamask-setup/index.md
- content/en/smart-contracts/fundamentals/erc-20-quickstart/index.md
Addresses https://github.com/filecoin-project/filecoin-docs/issues/2052
Note that the tabbed set of instructions for using chainlist in `metamask-setup` were slightly adjusted as well, as the add wallet flow on chainlist.network is different than the chainlist.org flow
> Replace chainlist.org links

- assets/scss/common/_global.scss
Closes https://github.com/filecoin-project/filecoin-docs/issues/1611
Also sets the first column of all tables to have a min-width of 20%.
> Fixes table no-wrap on long strings.

- .mdlinkcheck-config.json
Allows the pre commit link check to ignore 400 and 403 errors
> Link check: allow 400 and 403

- assets/js/index.js
- assets/js/progressbar.js
- assets/scss/layouts/_header.scss
- layouts/partials/footer/script-footer.html
- layouts/partials/header/header.html
Turns the top bar gradient into a fun little scrolls progress bar thing. The progress bar can be disabled by changing `progressBar` to `false` in `/config/_default/params.toml`.
This PR also disables the old search `index.js` file so we shouldn't get any more _Can't find `search`_ errors in the console anymore.
> Adds scrolls-progress-bar.

- content/en/networks/calibration/details/index.md
Calibration network was [reset](https://github.com/filecoin-project/community/discussions/74#discussioncomment-3946658) on 2022-11-01T18:13:00Z. The details in the docs are outdated. This PR updates it.
Sources:
https://calibration.filfox.info/en/tipset/0
https://github.com/filecoin-project/lotus/blob/master/build/bootstrap/calibnet.pi
> update calibration network details

- basics/interplanetary-consensus/ipc-agent.md
- networks/spacenet/get-test-tokens.md
A couple of links related to IPC are 503ing. This PR removes them for now. We should revert this PR once the links are back up.
> Changes 503ing links to codeblocks for now.

- nodes/implementations/README.md
Same as https://github.com/filecoin-project/filecoin-docs/pull/2144
Venus is written in Go and not in Rust.
> Fix Venus information

- networks/calibration/explorers.md
- networks/calibration/rpcs.md
- networks/mainnet/rpcs.md
Closes https://github.com/filecoin-project/filecoin-docs/issues/2213
> Uses api.node.glif.io addresses.

- networks/calibration/README.md
- networks/mainnet/README.md
- updated links for Forest generated latest snapshots
- new website link (hosted by the Forest team) for the entire Filecoin blockchain archival data [calibration net and main net]
> Filecoin blockchain archival data link(s)

- nodes/implementations/README.md
The current Forest description is out of date. Sending a PR with the most up-to-date information about the Forest node.
> Updated Forest Description 

- networks/calibration/README.md
- networks/calibration/rpcs.md
- networks/mainnet/README.md
- networks/mainnet/rpcs.md
- reference/general/README.md
- storage-providers/filecoin-deals/filecoin-programs.md
- Also adding quick links to the top of each network page to RPCs and Explorers
> Updating to Chainlist.org, now that deprecated testnets have been removed from their website

- WELCOME.md
It's been a while since legacy-docs.filecoin.io got deprecated. Ya'll can probably remove this message now.
> Removes legacy-docs.filecoin.io info message.

- networks/calibration/README.md
- networks/mainnet/README.md
- storage-providers/architecture/lotus-components.md
The FilOps Snapshots has been retired/replaced by the Forest snapshots. Update a link to the correct Lotus snapshot page.
> chore: Remove dead snapshot links

- basics/what-is-filecoin/networks.md
- networks/calibration/README.md
- smart-contracts/developing-contracts/get-test-tokens.md
- smart-contracts/developing-contracts/solidity-libraries.md
- smart-contracts/fundamentals/erc-20-quickstart.md
The calibration infra has been moved to ChainSafe. This updates the faucet links in the docs to the correct address.
> Update Calibnet-faucet links

- smart-contracts/filecoin-evm-runtime/precompiles.md
Nit change - there was a typo in the description of the precompiles file.
> Fixes Typo in PreCompiles.md Title

- networks/calibration/README.md
- networks/mainnet/README.md
This removes an update dependency and points to a known source of truth
> Removing list of bootstrap peers and pointing to Lotus source

- storage-providers/filecoin-deals/filecoin-programs.md
Issue:
- Gitbook doesn't like hyphenated alt texts and renders them as figcaptions.
- Github stars badges don't render the github octocat logo.
Fix:
- Remove hyphens in the alt texts
- Change styling to bigger, non-social badges
> Fix badge image alt texts and styling

- basics/assets/the-fil-token.md
- basics/how-storage-works/filecoin-plus.md
The page was a little out of date, and didn't cover all cases.
> update FIL token page to more accurately reflect current usage

- storage-providers/filecoin-deals/filecoin-programs.md
Remove the parenthesized outdated URLs in the headings of deprecated programs to clean up URL slugs and leave the deprecated badges' captions empty so Gitbook doesn't pick them up and print them out.
> Remove parenthesized URLs in headings and maintenance badges' captions

- basics/assets/metamask-setup.md
- reference/general/README.md
- smart-contracts/advanced/multicall.md
Removes references to Infura, which has no longer supports Filecoin as of Q3 2023.
> Fix infura docs references

- reference/general/README.md
- Waiting on clarity from pan for JS status. 
- Waiting on clarity from eva for filstats status
> Update Reference Doc

- nodes/lite-nodes/spin-up-a-lite-node.md
This PR updates the lite-node tutorial fixing multiple issues.
> Update lite node tutorial

- networks/mainnet/rpcs.md
To support https://github.com/filecoin-project/filecoin-docs/issues/2311
> Update RPCs with what API is supported and more links and auth info

- networks/mainnet/rpcs.md
- smart-contracts/fundamentals/README.md
- storage-providers/filecoin-deals/filecoin-programs.md
- storage-providers/filecoin-economics/fil-collateral.md
In lieu of https://github.com/filecoin-project/filecoin-docs/issues/2319 for now
Someone really needs to fix these things once per month and do a better job of keeping links updated
> Fixing all current broken links 

- README.md
- networks/mainnet/rpcs.md
- nodes/implementations/README.md
This is done in support of https://github.com/filecoin-project/filecoin-docs/issues/2319
> Fix broken links and update link checking docs

- WELCOME.md
- basics/what-is-filecoin/README.md
- basics/what-is-filecoin/blockchain.md
- basics/what-is-filecoin/crypto-economics.md
- basics/what-is-filecoin/networks.md
- basics/what-is-filecoin/programming-on-filecoin.md
- basics/what-is-filecoin/retrieval-market.md
- basics/what-is-filecoin/storage-market.md
- basics/what-is-filecoin/storage-model.md
- networks/calibration/explorers.md
- smart-contracts/advanced/oracles.md
- smart-contracts/developing-contracts/client-contract-tutorial.md
This PR improves readability and consistency in multiple sections of the Filecoin documentation, including updates to language flow, terminology alignment, and clearer explanations in key areas such as the storage model, retrieval market, blockchain, crypto-economics, networks, and programming on Filecoin.
> [UXIT-1706] Enhance Clarity and Consistency in ‘What is Filecoin’ Section

- networks/calibration/rpcs.md
- networks/mainnet/rpcs.md
This pull request adds new Lava RPC endpoints to the Filecoin documentation. Specifically:
- Added Lava mainnet and testnet endpoints under the relevant sections in the RPC documentation.
- Updated the table and listed the HTTPS endpoints for Lava, along with the corresponding documentation links.
These changes aim to provide developers and users with additional RPC options for interacting with Filecoin mainnet and testnet.
Please review and let me know if any adjustments are needed.
> Adding Lava RPC endpoints to Filecoin documentation

- storage-providers/filecoin-deals/filecoin-programs.md
update with minor typo at the [Filecoin programs and tools](https://docs.filecoin.io/storage-providers/filecoin-deals/filecoin-programs) docs page.
> docs: Update filecoin-programs.md

- nodes/lite-nodes/spin-up-a-lite-node.md
update with minor typo at [Spin up a lite-node](uhttps://docs.filecoin.io/nodes/lite-nodes/spin-up-a-lite-noderl) page
> docs: Update spin-up-a-lite-node.md

- .github/workflows/update-versions.yml
After this change, the workflow will only run when PRs are `opened` or `reopened`, but not when there is a new commit (`synchronize`).
> Fix remove synchronize from github action

- reference/exchanges/exchange-integration.md
- smart-contracts/filecoin-evm-runtime/difference-with-ethereum.md
Based on Slack convo with Steb here: https://filecoinproject.slack.com/archives/C0745JU645A/p1740700651512409?thread_ts=1740651550.989879&cid=C0745JU645A
> Updating Docs with important note about method numbers for sends to f410f/0x recipients

- reference/exchanges/exchange-integration.md
> Small fix to link format to internal docs

- .gitbook.yaml
This PR adds new redirects based on [this Insight Report from Gitbook ](https://app.gitbook.com/o/NNmD4UvLc26b1TmEYgzE/sites/site_5ZdFG/insights/urls)on broken links.
> [UXIT-2406] Add new redirects

- smart-contracts/filecoin-evm-runtime/difference-with-ethereum.md
fixes https://github.com/filecoin-project/ref-fvm/issues/1414
> FEVM: document the differences in the Filecoin BLOCKHASH instruction

- storage-providers/basics/README.md
Adds a new section to the Storage Provider Basics page explaining daily fees introduced in FIP-0100. Covers how fees are charged, fee debt behaviour, and startup readiness considerations for new SPs, including the 10 TiB threshold and delayed block rewards. Based on internal guidance and FIPs discussion thread #1105.
> Add FIP-0100 guidance

- storage-providers/pdp/README.md
- storage-providers/pdp/enable-pdp.md
- storage-providers/pdp/install-and-run-curio.md
- storage-providers/pdp/install-and-run-lotus.md
- storage-providers/pdp/use-pdp.md
Various updates to the PDP documentation section
> PDP documentation updates

- smart-contracts/fundamentals/erc-20-quickstart.md
Updated external links in the ERC-20 quickstart guide to open in new tabs, improving user experience by preventing navigation away from the documentation.
[Link to the dogfooding report](https://www.notion.so/filecoin/ERC20-Quickstart-Tutorial-Dogfooding-Report-ff3d5c84a55940ba9fde43c52d517696?pvs=4#a4c1e9831369479d8e2be0f20141bf9b)
> [ERC-20] Open Links in New Tab

- basics/assets/the-fil-token.md
- basics/how-storage-works/filecoin-and-ipfs.md
- basics/project-and-community/forums-and-FIPs.md
- networks/calibration/README.md
- smart-contracts/filecoin-evm-runtime/how-gas-works.md
- smart-contracts/fundamentals/support.md
- storage-providers/basics/README.md
The intention of this PR is to enhance the likelihood that these pages are surfaced more effectively in both external search engines and GitHub’s internal search.
Table also available in the ticket - [link here](https://www.notion.so/filecoin/Filecoin-Docs-Look-into-search-setting-for-most-searched-keywords-1dd7631f282580768c34f1e055f04ea6?source=copy_link) 
eventSearchQuery | eventsCount | visitorsCount | 1st result | Suggestion for the 1st result
-- | -- | -- | -- | --
gas | 12 | 7 | Gas | https://docs.filecoin.io/smart-contracts/filecoin-evm-runtime/how-gas-works Would be better than the JSON-RPC reference
staking | 11 | 10 | Networks | This should point to Glif or a page about defi staking 
stake | 8 | 7 | State | This should point to Glif or a page about defi staking
snapshot | 8 | 7 …
> Add keywords to multiple documentation files for improved SEO and discoverability

- .github/workflows/check-external-links.yml
Reverts filecoin-project/filecoin-docs#2410
> Revert "Running linkchecker on top of latest main instead of an old fork"
